const reviewNotes=require('./content-review-notes.cjs');
/* Build public static HTML. Run with Node; no packages or private inputs. */
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),docs=path.join(root,'docs');
const data=JSON.parse(fs.readFileSync(path.join(docs,'assets/site-content.json'),'utf8'));
const editorialPath=path.join(docs,'assets/site-editorial.json');
const editorial=fs.existsSync(editorialPath)?JSON.parse(fs.readFileSync(editorialPath,'utf8')):null;
require('./capability-contract.cjs').validate(data);
const reading=require('./reading-experience.cjs');
const navigation=require('./navigation-layout.cjs');
require('./build-feature-reference-svg.cjs').build();
require('./feature-specific-figures.cjs').build();
const references=require('./feature-reference-images.cjs');
references.validate(data);
const origin='https://youngteckhur.github.io/KDRUM-Public/';
const repo='https://github.com/YoungTeckHUR/KDRUM-Public/blob/main/';
const download='https://www.water.or.kr/kor/board/index.do?bid=BD_00026&menuId=15_126_128&mode=list';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(lang,ko,en)=>lang==='ko'?ko:en;
const get=(it,key,lang)=>it[key+(lang==='ko'?'Ko':'En')];
const statusKo={'ESTABLISHED':'확립된 기능','IMPLEMENTED / QA':'구현·검증 중','ACTIVE DEVELOPMENT':'개발 중','VALIDATED DEVELOPMENT':'개발·검증 중','RESEARCH FUNCTION':'연구 기능','DISABLED / REDEVELOPMENT':'비활성·재개발','ESTABLISHED / MODERNIZING':'확립·개선 중','RELEASE CANDIDATE':'공개 준비 중','EXPERIMENTAL':'연구 기능','SEPARATE DEVELOPMENT':'별도 개발'};
const statusEn={'ESTABLISHED':'Established','IMPLEMENTED / QA':'Implemented · QA','ACTIVE DEVELOPMENT':'In development','VALIDATED DEVELOPMENT':'Development validation','RESEARCH FUNCTION':'Research','DISABLED / REDEVELOPMENT':'Disabled · redevelopment','ESTABLISHED / MODERNIZING':'Established · modernizing','RELEASE CANDIDATE':'Release preparation','EXPERIMENTAL':'Research','SEPARATE DEVELOPMENT':'Separate development'};
function badge(s,lang){const type=s.startsWith('ESTABLISHED')?'established':s.includes('DISABLED')?'disabled':/RESEARCH|EXPERIMENTAL|RELEASE/.test(s)?'research':/DEVELOPMENT/.test(s)?'development':'';return `<span class="badge ${type}" data-status="${esc(s)}">${esc((lang==='ko'?statusKo:statusEn)[s]||s)}</span>`;}
function head(lang,title,desc,url,home=false){const pre=home&&lang==='ko'?'../':'';return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1">
<meta name="google-site-verification" content="6bVorUx-y-X0T3QGsCc57JBgOV071zBwRFJbmPsaaNI"><meta name="theme-color" content="#006da8">
<link rel="canonical" href="${origin+url}">${home?`\n<link rel="alternate" hreflang="en" href="${origin}"><link rel="alternate" hreflang="ko" href="${origin}ko/"><link rel="alternate" hreflang="x-default" href="${origin}">`:''}
<link rel="icon" href="${pre}assets/kdrum-symbol.png"><link rel="stylesheet" href="${pre}assets/site.css"><script defer src="${pre}assets/site.js"></script></head><body>
<a class="skip" href="#main">${t(lang,'본문으로 바로가기','Skip to content')}</a>`;}
function header(lang,pre='',page='home'){return `<header class="site-header"><div class="wrap header-row"><a class="brand" ${page==='media'?'data-media-home':''} href="${pre+(lang==='ko'?'ko/':'./')}"><img src="${pre}assets/kdrum-symbol.png" alt="" width="36" height="36">K-DRUM</a><nav class="header-links" aria-label="${t(lang,'자료와 언어','Resources and language')}"><a class="media-guide-link" href="${pre}media.html?lang=${lang}">${t(lang,'시각자료','Visual Guide')}</a><a class="nav-download" href="${download}">${t(lang,'무료 다운로드','Free download')}</a><div class="language"><a href="${pre||'./'}" lang="en" ${lang==='en'?'aria-current="page"':''}>English</a><a href="${pre}ko/" lang="ko" ${lang==='ko'?'aria-current="page"':''}>한국어</a></div></nav></div></header>`;}
// Korean home lives one directory below the site root.
function homeHeader(lang){return header(lang,lang==='ko'?'../':'');}
function footer(lang,pre=''){return `<footer class="site-footer"><div class="wrap footer-grid"><div><strong>K-DRUM</strong><p>K-water Grid-based Distributed Rainfall rUnoff Model</p><p>${t(lang,'K-DRUM 공개 기술자료 · 기능별 적용 범위와 개발 상태는 공개 기술문서에 명시되어 있습니다.','K-DRUM public technical information. Public technical documents define capability scope and development status.')}</p></div><div class="footer-links"><a href="${repo}PUBLICATION_POLICY.md">${t(lang,'공개자료 안내','Publication policy')}</a><a href="${repo}DEVELOPMENT_STATUS.md">${t(lang,'개발 상태','Development status')}</a><a href="${pre}seo-kdrum.html">${t(lang,'모형 소개 · FAQ','Model guide · FAQ')}</a></div></div></footer>`;}
function viewer(lang){return `<dialog id="image-viewer" aria-labelledby="image-caption"><div class="dialog-head"><strong>${t(lang,'그림 확대','Image detail')}</strong><label class="zoom-control"><span>${t(lang,'배율','Zoom')}</span><input type="range" min="1" max="3" step="0.5" value="1" aria-label="${t(lang,'그림 확대 배율','Image zoom level')}"></label><button type="button" aria-label="${t(lang,'닫기','Close')}">×</button></div><div class="dialog-body"><div class="image-pan" tabindex="0" aria-label="${t(lang,'확대 그림, 방향키로 이동','Enlarged image, scroll with arrow keys')}"><img alt=""></div><p id="image-caption"></p></div></dialog>`;}
function figure(name,lang,pre,caption){const file=`${pre}assets/diagrams/${name}-${lang}.svg`;return `<figure class="figure"><img src="${file}" alt="${esc(caption)}" width="960" height="600" loading="lazy"><figcaption><span>${esc(caption)}</span><a href="${file}" data-enlarge data-caption="${esc(caption)}">${t(lang,'그림 크게 보기 ↗','Enlarge diagram ↗')}</a></figcaption></figure>`;}
const domain={
 forcing:{diagram:'rainfall-grid',ko:'공간 강우 입력은 시간 간격과 단위를 맞춘 관측소 또는 격자 자료를 계산격자에 배분한 값입니다. 결측과 공간배분 오차는 유출 계산에 영향을 줍니다.',en:'Spatial rainfall inputs are station or gridded data mapped to computational cells with consistent intervals and units. Missing periods and mapping errors can affect runoff calculations.'},
 hydrology:{diagram:'grid-water-cycle',ko:'K-DRUM은 격자별 저장상태를 시간에 따라 갱신하며 강우, 침투, 증발산과 유출을 연결합니다. 초기상태와 연속 입력자료는 결과 해석의 주요 조건입니다.',en:'K-DRUM updates grid-cell storage through time to connect rainfall, infiltration, evapotranspiration and runoff. Initial states and continuous forcing are key conditions for interpreting results.'},
 terrain:{diagram:'model-workflow',ko:'생성된 유출은 격자와 하도 연결을 따라 전달됩니다. 사면과 하도는 각각의 지형자료와 경사·조도 표현을 갖습니다.',en:'Generated runoff moves through connected hillslope and channel cells. Hillslopes and channels have distinct terrain data, slopes and roughness representations.'},
 audit:{diagram:'read-results',ko:'결과의 타당성은 강우·유입·유출·저장량 변화의 일관성과 관측 비교 조건을 바탕으로 평가됩니다. 계산 종료만으로 결과의 타당성이 확보되지는 않습니다.',en:'Result validity is assessed through the consistency of rainfall, inflows, outflows and storage changes, together with observation-comparison conditions. Run completion alone does not establish validity.'},
 river:{diagram:'river-floodplain',ko:'하천 단면과 연결 구조, 경계조건을 함께 다루는 수리 확장입니다. 구조물과 운영 시나리오의 적용 범위는 각 기능의 개발 상태에 따라 달라집니다.',en:'Hydraulic extensions bring together cross sections, connectivity and boundary conditions. The scope of structures and operation scenarios depends on the development status of each feature.'},
 flood:{diagram:'river-floodplain',ko:'하천과 범람원의 교환은 연결 위치의 교환량과 저장량을 기준으로 평가됩니다. 제어된 개발 검증은 모든 유역에서의 적용성이나 인증을 의미하지 않습니다.',en:'River–floodplain exchange is assessed using exchange fluxes and storage at the connections. Controlled development validation does not imply universal applicability or certification.'},
 transport:{diagram:null,ko:'물의 흐름과 물질 수송은 서로 다른 해석 대상입니다. 연구 기능은 초기·경계조건과 대상 물질의 가정에 민감하며, 수질 기능은 비활성 상태로 현재 사용 가능한 기능에 포함되지 않습니다.',en:'Water flow and material transport are distinct processes. Research functions depend on initial and boundary conditions and material assumptions. Water-quality functionality is disabled and is not currently available.'},
 platform:{diagram:'program-workflow',ko:'입력 작성, 계산, 출력 저장과 결과 분석은 프로그램별로 구분된 역할입니다. 각 프로그램의 공개 여부와 개발 상태는 Core의 확립된 수문 기능과 별도로 관리됩니다.',en:'Input preparation, computation, output storage and result analysis have distinct roles across the programs. Each program has its own availability and development status, separate from established Core hydrology.'}
};
function capability(it,lang,pre){return navigation.capability(it,lang,pre,{badge,data,repo,reading});}
function sectionTitle(lang,n,title,desc){return `<div class="section-heading"><div><span class="index">${n}</span><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div></div>`;}
function buildHome(lang){const ko=lang==='ko',pre=ko?'../':'';const L=(k,e)=>t(lang,k,e);const nav=[['overview',L('모형 소개','Overview')],['capabilities',L('주요 기능','Capabilities')],['results',L('결과 해석','Results')],['programs',L('프로그램','Programs')],['research',L('연구·자료','Research')],['download',L('다운로드','Download')]];
 let html=head(lang,L('K-DRUM | 분포형 강우유출·하천수리·홍수해석','K-DRUM | Distributed hydrology, river hydraulics and flood analysis'),L('K-water의 격자단위 분포형 강우유출모형 K-DRUM. 확립된 수문 기능과 개발 중인 수리 확장, 공개 연구 및 시각자료를 제공하는 공식 기술 홈페이지입니다.','Official technical information on K-water’s grid-based distributed hydrologic model: established hydrology, hydraulic extensions in development, public research and visual guides.'),ko?'ko/':'',true)+homeHeader(lang);
 html+=`<main id="main"><section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">${L('유역에서 하천까지 이어지는 물의 흐름','Water flow, from watershed to river')}</p><h1>K-DRUM</h1><p class="full-name">K-water Grid-based Distributed Rainfall rUnoff Model</p><p class="lead">${L('강우와 유역의 공간적 차이를 반영하는 분포형 수문모형.','Distributed hydrology that represents rainfall and the spatial differences of a watershed.')}</p><p class="support">${L('K-water가 개발한 물리 기반 격자단위 강우유출모형입니다. 강우·침투·저류·유출을 연결하는 수문 기능을 중심으로 하천수리와 홍수범람 해석을 확장하고 있습니다.','Developed by K-water, K-DRUM connects rainfall, infiltration, storage and runoff on computational grids. River hydraulics and floodplain analysis are active extensions of this hydrologic foundation.')}</p><div class="actions"><a class="button primary" href="#overview">${L('모형 개요','Model overview')}</a><a class="button" href="${download}">${L('MyWater 무료 다운로드','Free download · MyWater')} ↗</a></div><div class="brand-credit"><a href="https://www.kwater.or.kr/kiwe/main.do"><img src="${pre}assets/kwater-ci.png" alt="K-water" width="84" height="36"></a><span>${L('공개 연구에 기반한 수문모형','Hydrology grounded in public research')}</span></div></div><figure class="hero-image"><img src="${pre}assets/visuals/kdrum-watershed-hero-HQ.jpg" width="886" height="760" fetchpriority="high" alt="${L('유역 지형, 계산격자와 하천망을 함께 표현한 개념 이미지','Concept image of watershed terrain, computational grids and a river network')}"><figcaption>${L('모형 이해를 돕는 개념 이미지이며 실제 수치모의 결과가 아닙니다.','Concept image for model introduction; not a numerical simulation result.')}</figcaption></figure></div></section><nav class="site-nav" aria-label="${L('본문 탐색','Page sections')}"><div class="wrap">${nav.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}</div></nav>`;
 html+=`<section class="section" id="overview"><div class="wrap">${sectionTitle(lang,'01 · K-DRUM',L('같은 비에도, 유역의 반응은 다릅니다.','The same rain can produce a different response.'),L('K-DRUM은 강우의 위치, 지형, 토양과 저장상태를 격자별로 반영하여 물의 이동을 해석합니다.','Rainfall location, terrain, soil and storage states shape the movement of water across computational cells.'))}<div class="intro-grid"><article class="intro-block">${badge('ESTABLISHED',lang)}<h3>${L('격자 수문과 유출 전달','Grid hydrology and runoff routing')}</h3><p>${L('공간 강우, 침투, 지표·지표하 유출과 운동파 흐름추적이 모형의 수문 기반을 이룹니다.','Spatial rainfall, infiltration, surface/subsurface runoff and kinematic-wave routing form the hydrologic foundation.')}</p></article><article class="intro-block">${badge('ESTABLISHED',lang)}<h3>${L('사상에서 연속 물수지까지','From events to continuous water balance')}</h3><p>${L('K-DRUM은 토양수분, 증발산과 적설·융설을 시간에 따라 연결하여 연속적인 유역 상태를 계산합니다.','K-DRUM connects soil water, evapotranspiration and snow storage/melt through time for continuous watershed simulation.')}</p></article><article class="intro-block">${badge('ACTIVE DEVELOPMENT',lang)}<h3>${L('하천수리와 홍수범람 확장','River and floodplain extensions')}</h3><p>${L('1D 하천망, 구조물, 1D–2D 교환과 범람 해석은 기능별로 서로 다른 개발·검증 범위를 갖습니다.','1D networks, hydraulic structures, 1D–2D exchange and floodplain analysis have feature-specific development and validation boundaries.')}</p></article></div>${figure('model-workflow',lang,pre,L('확립된 수문 기반과 개발 중인 수리 확장을 구분한 전체 계산 흐름.','The calculation path distinguishes established hydrology from hydraulic extensions in development.'))}<div class="feature-reading"><div><h3>${L('한 격자에서의 물순환','Water movement within a cell')}</h3><p>${domain.hydrology[lang]}</p>${figure('grid-water-cycle',lang,pre,L('물의 저장과 이동을 구분한 개념도.','Concept diagram distinguishing water storage from transfers.'))}</div><div><h3>${L('관측자료에서 공간 강우로','From observations to spatial rainfall')}</h3><p>${domain.forcing[lang]}</p>${figure('rainfall-grid',lang,pre,L('자료 입력과 공간배분 과정을 설명하는 예시.','An illustration of input data and spatial allocation.'))}</div></div>${reading.quickLinks(lang)}</div></section>`;

 html+=reading.visualConcept(lang,pre);
 html+=`<section class="section soft" id="capabilities"><div class="wrap">${sectionTitle(lang,'02 · CAPABILITIES',L('주요 기능과 적용 범위','Capabilities and application scope'),L('기능을 분야별로 선택해 활용 목적, 핵심 원리, 입력·계산 흐름과 개발 상태를 살펴볼 수 있습니다. 연구·실험 기능은 확립 기능과 구분합니다.','Browse capabilities by area to review purpose, mechanism, input/calculation flow and development status. Research and experimental functions are separated from established capabilities.'))}<div class="filters" id="feature-filters" hidden><label>${L('분야','Category')}<select id="feature-group"><option value="">${L('전체 분야','All categories')}</option>${data.groups.map(g=>`<option value="${g.id}">${esc(g[lang])}</option>`).join('')}</select></label><label>${L('기능 검색','Find a capability')}<input type="search" id="feature-search" aria-describedby="feature-search-help" placeholder="${L('예: 강우, 물수지, NetCDF','e.g. rainfall, water balance, NetCDF')}"></label></div><p id="feature-search-help" class="feature-search-help" hidden>${L('검색어를 입력하면 전체 분야에서 찾습니다. 한글·영문 모두 검색할 수 있습니다.','Typing searches all categories. Korean and English terms are supported.')}</p><div class="feature-search-status"><p id="feature-count" class="result-count" aria-live="polite">46 ${L('개 항목','entries')}</p><button type="button" id="feature-reset" class="feature-link-button" hidden>${L('전체 기능 보기','Show all capabilities')}</button></div><div class="capability-grid">${data.items.map(it=>capability(it,lang,pre)).join('\n')}</div><p class="no-results" id="no-results" hidden>${L('선택한 분야와 검색어에 일치하는 항목이 없습니다.','No entries match the selected category and search terms.')}</p><div class="note">${L('기술 상태 기준: 2026-09-21 공개 설명·상태 경계 재검토. 기능 상태는 수치검증 없이 상향하지 않았으며, 개발 검증은 제한된 조건의 확인으로 모든 유역의 인증을 뜻하지 않습니다.','Technical status follows the September 21, 2026 public wording and maturity-boundary review. No capability was promoted without new numerical validation; development validation remains condition-specific rather than universal certification.')} <a href="${repo}DEVELOPMENT_STATUS.md">${L('전체 상태 기준','Full status reference')} ↗</a></div></div></section>`;
 html+=`<section class="section" id="results"><div class="wrap">${sectionTitle(lang,'03 · RESULTS',L('시간·공간별 결과와 활용','Results in time and space'),L('결과의 시간·공간 특성을 설명하는 개념도이며 실제 유역 계산값은 아닙니다. 계산 완료, 물수지 일관성 및 관측 비교는 서로 다른 평가 항목입니다.','These diagrams illustrate temporal and spatial characteristics of results; they are not calculations from a real basin. Run completion, water-balance consistency and observation comparisons are distinct evaluation criteria.'))}<div class="results-layout">${figure('read-results',lang,pre,L('수문곡선의 시간·유량 축과 물수지 구성 항목.','Time and discharge axes of a hydrograph, with the components of a water balance.'))}<div class="results-notes"><div><h3>${L('침수 후보지도와 동적 해석','Candidate maps and dynamic analysis')}</h3><p>${L('별도 침수영역 매핑은 지형·수위원·허용 영역으로 침수 후보영역을 산정합니다. 시간에 따른 수심·유량을 계산하는 2D 수리해석과 구분하고, 결과 파일을 만든 계산 경로부터 확인하세요.','Separate flood-area mapping estimates candidate inundation areas from terrain, water-level sources and an allowed domain. Distinguish it from dynamic 2D depth/flow simulation; first identify which calculation path produced the file.')}</p></div><div><h3>${L('공간분포','Spatial patterns')}</h3><p>${L('강우·토양수분·유출의 공간분포는 동일한 영역과 시간 범위에서 비교됩니다. 범람 관련 출력의 적용 범위는 해당 수리 기능의 개발 상태에 따릅니다.','Rainfall, soil water and runoff distributions support comparison over a common domain and period. The scope of flood outputs depends on the development status of the hydraulic function.')}</p></div><div><h3>${L('수문곡선','Hydrographs')}</h3><p>${L('수문곡선은 관측과 계산의 첨두, 발생 시점 및 감수부 특성을 비교하는 자료입니다. 비교 기준은 동일한 단위와 시간 간격입니다.','Hydrographs support comparison of observed and calculated peaks, timing and recession behavior using consistent units and time intervals.')}</p></div><div><h3>${L('물수지','Water balance')}</h3><p>${L('물수지 평가는 유입·유출·저장량 변화·손실의 정의와 집계 범위를 기준으로 합니다. 실행 성공만으로 물수지의 타당성이나 예측 정확도가 입증되지는 않습니다.','Water-balance evaluation uses the definitions and accounting domain of inputs, outputs, storage and losses. Execution success alone establishes neither balance nor predictive accuracy.')}</p></div></div></div><div class="diagram-panel"><h3>${L('하천과 범람원, 연결되는 두 계산 영역','River and floodplain: two connected domains')}</h3>${badge('ACTIVE DEVELOPMENT',lang)}${figure('river-floodplain',lang,pre,L('하천–범람원 교환 개념도. 제어된 개발 검증과 실유역 적용성은 서로 다른 평가 범위입니다.','Conceptual river–floodplain exchange. Controlled validation and basin applicability are distinct.'))}</div></div></section>`;
 const programIds=['inputstudio','viewer','channelbed','netcdf','river-viewer','estuary'];
 html+=`<section class="section soft" id="programs"><div class="wrap">${sectionTitle(lang,'04 · PROGRAMS',L('프로그램·결과 형식과 역할','Programs, output format and roles'),domain.platform[lang])}${figure('program-workflow',lang,pre,L('프로그램의 역할과 데이터 교환 관계.','Program roles and the exchange of data.'))}<div class="program-grid"><article class="program"><h3>K-DRUM Core</h3>${badge('ESTABLISHED',lang)}<p>${L('K-DRUM Core는 확립된 분포형 수문과 운동파 추적을 중심으로 구성됩니다. Core 내부의 수리·범람 확장에는 기능별 개발 상태가 적용되며, 모두 확립된 기능은 아닙니다.','K-DRUM Core is built around established distributed hydrology and kinematic routing. Hydraulic and flood extensions within Core retain their feature-specific development status and are not all established capabilities.')}</p></article>${programIds.map(id=>{const it=data.items.find(i=>i.id===id);return `<article class="program"><h3>${esc(it[lang])}</h3>${badge(it.s,lang)}<p>${esc(get(it,'sum',lang))}</p>${id==='river-viewer'?`<p class="small">${L('아직 공개 배포되지 않았습니다.','Not yet publicly distributed.')}</p>`:''}</article>`;}).join('')}</div></div></section>`;
 html+=`<section class="section" id="research"><div class="wrap">${sectionTitle(lang,'05 · RESEARCH',L('공개 연구와 적용 사례','Applications grounded in public research.'),L('공개 연구는 대상 유역, 입력자료와 적용 범위에 따른 K-DRUM의 활용 사례를 제시합니다.','Public studies document K-DRUM applications within the basin settings, input data and scope of each study.'))}<div class="stories">${renderStories(lang)}</div><div class="resource-links"><a href="${repo}PUBLICATIONS.md">${L('전체 논문과 원문 출처','All publications and sources')} ↗</a><a href="${repo}CAPABILITIES.md">${L('기능 설명','Capabilities')} ↗</a><a href="${repo}MODEL_CARD.md">Model Card ↗</a><a href="${pre}media.html?lang=${lang}">${L('발표자료·영상·18개 기능 이미지','Presentation, video and 18 feature images')} ↗</a></div></div></section>`;
 html+=`<section class="section soft" id="download"><div class="wrap download-layout"><div>${sectionTitle(lang,'06 · DOWNLOAD',L('공식 배포와 이용 조건','Official distribution and terms of use'),L('K-DRUM의 공식 배포 자료와 이용 안내는 MyWater에서 제공됩니다.','MyWater provides official K-DRUM materials and distribution information.'))}<a class="button primary" href="${download}">${L('MyWater 무료 다운로드','Free download from MyWater')} ↗</a></div><div><h3>${L('배포 버전과 적용 범위','Distribution version and application scope')}</h3><ol><li>${L('배포 버전, 동봉 문서와 이용 조건은 MyWater 배포 페이지에 명시되어 있습니다.','The MyWater distribution page specifies the package version, accompanying documentation and terms of use.')}</li><li>${L('현재 Core 개발 계열은 v3.x입니다. 개발·시험 기능과 MyWater 공식 배포본의 포함 기능은 다를 수 있습니다.','The current Core development line is v3.x. Development/test features may differ from those in the official MyWater package.')}</li><li>${L('모형의 적용 범위는 대상 유역의 자료·적용 조건과 기능별 검증 범위에 따라 달라집니다.','Model applicability depends on basin data, application conditions and feature-specific validation scope.')}</li></ol><div class="resource-links"><a href="${pre}assets/qr/official/KDRUM_QR_Standalone_Vector.svg" download>${L('홈페이지 공유 QR · SVG','Homepage sharing QR · SVG')} ↗</a><a href="${pre}seo-kdrum.html">${L('모형 소개와 자주 묻는 질문','Model guide and FAQ')} ↗</a><a href="https://www.kwater.or.kr/kiwe/main.do">${L('K-water 연구원','K-water Research Institute')} ↗</a></div></div></div></section></main>`;
 return navigation.compose(html+footer(lang,pre)+viewer(lang)+'</body></html>\n',lang,{data});
}
function renderStories(lang){if(!editorial)return `<article class="story"><h3>${t(lang,'공개 연구 목록','Public research records')}</h3><p>${t(lang,'공개 연구 목록은 레이더 강우, 장기 융설과 지표수·지하수 연계 연구의 원문 출처를 제공합니다.','Public research records provide original sources on radar rainfall, snowmelt and surface/groundwater integration.')}</p><a href="${repo}PUBLICATIONS.md">${t(lang,'논문 목록','Publications')} ↗</a></article>`;return editorial.stories.map(st=>{const s=st[lang];return `<article class="story"><p class="eyebrow">${esc(st.year)}</p><h3>${esc(s.title)}</h3><p><strong>${esc(s.question)}</strong></p><p>${esc(s.context)}</p><p>${esc(s.method)}</p><p class="scope">${esc(s.scope)}</p><p class="citation"><a href="${esc(st.link)}">${esc(st.paperTitle)} ↗</a></p></article>`;}).join('');}
for(const lang of ['en','ko'])fs.writeFileSync(path.join(docs,lang==='en'?'index.html':'ko/index.html'),buildHome(lang));
function buildMedia(){const m=data.media;const asset='media/2026-09-12-p18/';const translated=(key)=>['ko','en'].map(lang=>`<span data-language="${lang}" ${lang==='en'?'hidden':''}>${esc(m.txt[lang][key])}</span>`).join('');
 const mediaHeader=`<header class="site-header"><div class="wrap header-row"><a class="brand" data-media-home href="ko/"><img src="assets/kdrum-symbol.png" width="36" height="36" alt="">K-DRUM</a><nav class="media-toolbar" aria-label="Language"><a href="?lang=ko" data-media-lang="ko" lang="ko" aria-current="page">한국어</a><a href="?lang=en" data-media-lang="en" lang="en">English</a></nav></div></header>`;
 let h=head('ko','K-DRUM 시각자료 | p18 공개 갤러리',m.txt.ko.intro,'media.html')+mediaHeader;
 h+=`<main id="main" data-media-page><div class="wrap"><div class="page-title"><p class="eyebrow">VISUAL GUIDE · P18</p><h1>${translated('title')}</h1><p>${translated('intro')}</p></div><div class="video-layout"><video controls playsinline preload="metadata" poster="${asset}07_Digital_Reference.png"><source src="${asset}KDRUM_Nature_to_Digital_22s_web.mp4" type="video/mp4"></video><div><h2>${translated('videoTitle')}</h2><p id="videoText">${translated('videoText')}</p><div class="actions"><a id="pdfBtn" class="button primary" href="${asset}K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${translated('pdf')} ↗</a><a class="button" href="${asset}KDRUM_Nature_to_Digital_22s_web.mp4">${translated('video')} ↗</a></div></div></div><div class="note">${translated('note')} <a href="${repo}DEVELOPMENT_STATUS.md">DEVELOPMENT_STATUS ↗</a> · <a href="${repo}CAPABILITIES.md">CAPABILITIES ↗</a></div>`;
 h+=`<div id="review-notes">${reviewNotes.review('ko')}${reviewNotes.review('en')}</div>`;
 for(const lang of ['ko','en']){h+=`<div data-language="${lang}" lang="${lang}" id="gallery-${lang}" ${lang==='en'?'hidden':''}>`;for(const g of m.data){h+=`<section class="gallery-group"><h2>${g[0]} · ${esc(g[lang==='ko'?2:1])}</h2><div class="gallery-grid">`;for(const it of g[3]){const title=it[lang==='ko'?2:1],description=it[lang==='ko'?4:3],status=m.featureStatus[it[0]][lang==='ko'?1:0],src='assets/presentation/2026-09-12-p18/'+m.featureFiles[it[0]];h+=`<article class="media-card"><a href="${src}" data-enlarge data-caption="${esc(title+' · '+status)}" aria-label="${esc(title)} ${t(lang,'확대','— enlarge')}"><img class="thumb" src="${src}" alt="${esc(title)}" width="1600" height="900" loading="lazy" decoding="async"></a><div class="media-body"><span class="badge">${esc(status)}</span><h3>${esc(title)}</h3><p>${esc(description)}</p>${reviewNotes.cardNote(it[0],lang)}<a class="enlarge" href="${src}" data-enlarge data-caption="${esc(title+' · '+status)}">${t(lang,'이미지 확대','Enlarge image')} ↗</a></div></article>`;}h+='</div></section>';}h+='</div>';}
 h+=`<section class="gallery-group"><h2>${translated('resources')}</h2><div class="resource-links"><a href="${asset}K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${translated('rPdf')} ↗</a><a href="${asset}KDRUM_Nature_to_Digital_22s_web.mp4">${translated('rVideo')} ↗</a><a href="${asset}07_Digital_Reference.png">${translated('rImage')} ↗</a></div><p class="small">${translated('foot')}</p></section><noscript><p>이 페이지는 한국어로 제공됩니다. The Korean gallery and all original media links work without JavaScript; language switching requires JavaScript.</p></noscript></div></main>`;
 return h+`<div data-language="ko">${footer('ko')}</div><div data-language="en" hidden>${footer('en')}</div>`+viewer('ko')+'</body></html>\n';}
function buildGuide(){let h=head('ko','K-DRUM 모형 소개 · 자주 묻는 질문','K-water Grid-based Distributed Rainfall rUnoff Model의 주요 입력·출력, 개발 상태, 공식 배포 및 공개 기술자료.','seo-kdrum.html')+header('ko');h+=`<main id="main"><div class="wrap faq-layout"><div class="page-title"><p class="eyebrow">MODEL GUIDE</p><h1>K-DRUM 모형 소개</h1><p>K-water Grid-based Distributed Rainfall rUnoff Model</p><p>K-DRUM의 적용 범위, 주요 입력·출력과 공식 배포 정보입니다. 확립된 수문 기능과 개발·연구 단계의 확장은 각각의 개발 및 공개 상태에 따라 구분됩니다.</p><div class="resource-links"><a href="ko/">한국어 홈페이지 ↗</a><a href="./" lang="en">English homepage ↗</a><a href="media.html?lang=ko">시각자료 ↗</a></div></div>`;
 for(const lang of ['ko','en']){h+=`<section class="section" lang="${lang}"><h2>${t(lang,'자주 묻는 질문','Frequently asked questions')}</h2>${(editorial?.faqs||[]).map(f=>`<details class="faq" ${lang==='ko'?'open':''}><summary>${esc(f[lang].question)}</summary><p>${esc(f[lang].answer)}</p></details>`).join('')}</section>`;}
 h+=`<div class="note">기능 상태 기준은 2026-09-21 공개 설명·상태 경계 재검토입니다. <a href="${repo}DEVELOPMENT_STATUS.md">DEVELOPMENT_STATUS</a> 및 <a href="${repo}MODEL_CARD.md">Model Card</a>에 기능별 범위와 개발 상태가 명시되어 있습니다.</div><section class="section"><h2>공개 자료</h2><div class="resource-links"><a href="${repo}PUBLICATIONS.md">논문과 출처 ↗</a><a href="${repo}CAPABILITIES.md">기능 설명 ↗</a><a href="${download}">MyWater 무료 배포 안내 ↗</a></div></section></div></main>`;
 const jsonld={'@context':'https://schema.org','@type':'SoftwareApplication',name:'K-DRUM',alternateName:'K-water Grid-based Distributed Rainfall rUnoff Model',applicationCategory:'ScientificApplication',description:'Physically based grid-distributed hydrologic model developed by K-water, with hydraulic extensions in development.',url:origin,publisher:{'@type':'Organization',name:'K-water'},sameAs:['https://github.com/YoungTeckHUR/KDRUM-Public']};
 // Preserve the existing SEO page social image; do not generate a new one.
 h=h.replace('</head>',`<meta property="og:title" content="K-DRUM | K-water 분포형 강우유출모형"><meta property="og:description" content="K-water의 물리 기반 격자형 분포형 수문모형 K-DRUM 공개 기술정보"><meta property="og:type" content="website"><meta property="og:url" content="${origin}seo-kdrum.html"><meta property="og:image" content="${origin}assets/visuals/kdrum-watershed-hero-HQ.jpg"><script type="application/ld+json">${JSON.stringify(jsonld)}</script></head>`);
 return h+footer('ko')+'</body></html>\n';}
fs.writeFileSync(path.join(docs,'media.html'),buildMedia());
fs.writeFileSync(path.join(docs,'seo-kdrum.html'),buildGuide());
module.exports={head,header,footer,viewer,figure,esc,t,origin,repo,docs,data};
