/* Build public static HTML. Run with Node; no packages or private inputs. */
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),docs=path.join(root,'docs');
const data=JSON.parse(fs.readFileSync(path.join(docs,'assets/site-content.json'),'utf8'));
const editorialPath=path.join(docs,'assets/site-editorial.json');
const editorial=fs.existsSync(editorialPath)?JSON.parse(fs.readFileSync(editorialPath,'utf8')):null;
const origin='https://youngteckhur.github.io/KDRUM-Public/';
const repo='https://github.com/YoungTeckHUR/KDRUM-Public/blob/main/';
const download='https://www.water.or.kr/kor/board/index.do?bid=BD_00026&menuId=15_126_128&mode=list';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(lang,ko,en)=>lang==='ko'?ko:en;
const get=(it,key,lang)=>it[key+(lang==='ko'?'Ko':'En')];
const statusKo={'ESTABLISHED':'확립된 기능','IMPLEMENTED / QA':'구현 · QA','ACTIVE DEVELOPMENT':'개발 중','VALIDATED DEVELOPMENT':'개발 단계 검증','RESEARCH FUNCTION':'연구 기능','DISABLED / REDEVELOPMENT':'비활성 · 재개발 후보','ESTABLISHED / MODERNIZING':'확립 · 현대화 진행','RELEASE CANDIDATE':'릴리스 후보','EXPERIMENTAL':'실험 연구','SEPARATE DEVELOPMENT':'별도 개발 · 미공개'};
function badge(s,lang){const type=s.startsWith('ESTABLISHED')?'established':s.includes('DISABLED')?'disabled':/RESEARCH|EXPERIMENTAL|RELEASE/.test(s)?'research':/DEVELOPMENT/.test(s)?'development':'';return `<span class="badge ${type}" data-status="${esc(s)}">${esc(lang==='ko'?statusKo[s]||s:s)}</span>`;}
function head(lang,title,desc,url,home=false){const pre=home&&lang==='ko'?'../':'';return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large,max-video-preview:-1">
<meta name="google-site-verification" content="6bVorUx-y-X0T3QGsCc57JBgOV071zBwRFJbmPsaaNI"><meta name="theme-color" content="#006da8">
<link rel="canonical" href="${origin+url}">${home?`\n<link rel="alternate" hreflang="en" href="${origin}"><link rel="alternate" hreflang="ko" href="${origin}ko/"><link rel="alternate" hreflang="x-default" href="${origin}">`:''}
<link rel="icon" href="${pre}assets/kdrum-symbol.png"><link rel="stylesheet" href="${pre}assets/site.css"><script defer src="${pre}assets/site.js"></script></head><body>
<a class="skip" href="#main">${t(lang,'본문으로 바로가기','Skip to content')}</a>`;}
function header(lang,pre='',page='home'){return `<header class="site-header"><div class="wrap header-row"><a class="brand" ${page==='media'?'data-media-home':''} href="${pre+(lang==='ko'?'ko/':'./')}"><img src="${pre}assets/kdrum-symbol.png" alt="" width="36" height="36">K-DRUM</a><nav class="header-links" aria-label="${t(lang,'자료와 언어','Resources and language')}"><a class="media-guide-link" href="${pre}media.html?lang=${lang}">${t(lang,'시각자료','Visual Guide')}</a><a class="nav-download" href="${download}">${t(lang,'무료 다운로드','Free download')}</a><div class="language"><a href="${pre||'./'}" lang="en" ${lang==='en'?'aria-current="page"':''}>English</a><a href="${pre}ko/" lang="ko" ${lang==='ko'?'aria-current="page"':''}>한국어</a></div></nav></div></header>`;}
// Korean home lives one directory below the site root.
function homeHeader(lang){return header(lang,lang==='ko'?'../':'');}
function footer(lang,pre=''){return `<footer class="site-footer"><div class="wrap footer-grid"><div><strong>K-DRUM</strong><p>K-water Grid-based Distributed Rainfall rUnoff Model</p><p>${t(lang,'공개 기술자료 · 기능의 적용 범위와 개발 상태는 공개 문서를 기준으로 확인해 주세요.','Public technical information. Consult the public documents for capability scope and development status.')}</p></div><div class="footer-links"><a href="${repo}PUBLICATION_POLICY.md">${t(lang,'공개자료 안내','Publication policy')}</a><a href="${repo}DEVELOPMENT_STATUS.md">${t(lang,'개발 상태','Development status')}</a><a href="${pre}seo-kdrum.html">${t(lang,'모형 소개 · FAQ','Model guide · FAQ')}</a></div></div></footer>`;}
function viewer(lang){return `<dialog id="image-viewer" aria-labelledby="image-caption"><div class="dialog-head"><strong>${t(lang,'그림 확대','Image detail')}</strong><label class="zoom-control"><span>${t(lang,'배율','Zoom')}</span><input type="range" min="1" max="3" step="0.5" value="1" aria-label="${t(lang,'그림 확대 배율','Image zoom level')}"></label><button type="button" aria-label="${t(lang,'닫기','Close')}">×</button></div><div class="dialog-body"><div class="image-pan" tabindex="0" aria-label="${t(lang,'확대 그림, 방향키로 이동','Enlarged image, scroll with arrow keys')}"><img alt=""></div><p id="image-caption"></p></div></dialog>`;}
function figure(name,lang,pre,caption){const file=`${pre}assets/diagrams/${name}-${lang}.svg`;return `<figure class="figure"><img src="${file}" alt="${esc(caption)}" width="960" height="600" loading="lazy"><figcaption><span>${esc(caption)}</span><a href="${file}" data-enlarge data-caption="${esc(caption)}">${t(lang,'그림 크게 보기 ↗','Enlarge diagram ↗')}</a></figcaption></figure>`;}
const domain={
 forcing:{diagram:'rainfall-grid',ko:'강우의 시간 간격과 단위를 맞춘 뒤 관측소 또는 격자 자료의 공간배분 결과를 확인합니다. 결측이나 공간배분 오차는 이후 유출 계산에도 영향을 줍니다.',en:'Align rainfall intervals and units, then inspect the spatial mapping of station or gridded data. Missing periods and mapping errors can affect the runoff calculation.'},
 hydrology:{diagram:'grid-water-cycle',ko:'격자별 저장상태를 시간에 따라 갱신하면서 강우, 침투, 증발산과 유출을 연결합니다. 초기상태와 연속 입력자료가 결과 해석의 중요한 조건입니다.',en:'Update grid-cell storage through time to connect rainfall, infiltration, evapotranspiration and runoff. Initial states and continuous forcing are important conditions for interpreting results.'},
 terrain:{diagram:'model-workflow',ko:'생성된 유출은 격자와 하도 연결을 따라 전달됩니다. 사면·하도의 지형자료와 서로 다른 경사·조도 표현을 구분해 검토합니다.',en:'Generated runoff moves through connected hillslope and channel cells. Review their terrain data and distinct slope and roughness representations.'},
 audit:{diagram:'read-results',ko:'계산이 종료됐다는 사실과 결과가 타당하다는 판단은 다릅니다. 강우·유입·유출·저장량 변화의 일관성과 관측 비교 조건을 함께 점검합니다.',en:'Completing a run does not by itself establish result validity. Check rainfall, inflows, outflows and storage changes alongside the conditions used for observation comparisons.'},
 river:{diagram:'river-floodplain',ko:'하천 단면과 연결 구조, 경계조건을 함께 다루는 수리 확장입니다. 구조물과 운영 시나리오의 적용 범위는 각 기능의 개발 상태에 따라 검토해야 합니다.',en:'Hydraulic extensions bring together cross sections, connectivity and boundary conditions. The scope of structures and operation scenarios must be reviewed against each feature’s development status.'},
 flood:{diagram:'river-floodplain',ko:'하천과 범람원의 연결 위치에서 교환량과 저장량을 함께 검토합니다. 제어된 개발 검증은 모든 유역에서의 적용성이나 인증을 의미하지 않습니다.',en:'Review exchange fluxes and storage at connections between river and floodplain. Controlled development validation does not imply universal applicability or certification.'},
 transport:{diagram:null,ko:'물의 이동과 물질의 이동을 구분해 해석합니다. 연구 기능은 초기·경계조건과 대상 물질의 가정에 민감하며, 비활성 수질 기능은 사용 가능한 기능으로 소개하지 않습니다.',en:'Distinguish water movement from material transport. Research functions depend on initial and boundary conditions and material assumptions. Disabled water-quality functionality is not presented as available.'},
 platform:{diagram:'program-workflow',ko:'입력 작성, 계산, 출력 저장과 결과 검토는 서로 다른 역할입니다. 프로그램별 공개 여부와 성숙도는 Core의 수문 기능 상태와 별개로 확인합니다.',en:'Input preparation, computation, output storage and result review have distinct roles. Check each program’s availability and maturity separately from the established Core hydrology.'}
};
function capability(it,lang,pre){const d=domain[it.g];const steps=get(it,'steps',lang)||[];return `<details class="capability" id="cap-${it.id}" data-group="${it.g}" data-feature="${it.id}" data-status="${esc(it.s)}"><summary>${badge(it.s,lang)}<h3>${esc(it[lang])}</h3><p>${esc(get(it,'sum',lang))}</p></summary><div class="cap-detail"><div class="detail-grid"><div><h4>${t(lang,'계산에 연결되는 자료와 과정','Data and process')}</h4><ol>${steps.map((s,i)=>`<li><strong>${it.id==='rain-summary'?t(lang,'자료 구분','Data category'):t(lang,['입력·상태','처리·계산','결과·확인'][i],['Input / state','Processing','Output / review'][i])}</strong> — ${esc(s)}</li>`).join('')}</ol></div><div><h4>${t(lang,'이 기능을 해석하는 방법','How to interpret this capability')}</h4><p>${esc(d[lang])}</p></div></div><div class="detail-status"><h4>${t(lang,'현재 공개 상태','Current public status')}</h4><p>${esc(get(it,'now',lang))}</p></div>${d.diagram?figure(d.diagram,lang,pre,t(lang,'기능군의 설명용 개념도입니다. 개별 기능의 적용 범위는 위 상태와 함께 확인하세요.','Concept diagram for this process family. Read it alongside the individual feature’s status above.')):''}<div class="resource-links"><a href="${repo}CAPABILITY_ATLAS.md">${t(lang,'기능별 공개 근거','Public capability reference')} ↗</a><a href="${repo}DEVELOPMENT_STATUS.md">${t(lang,'개발 상태와 범위','Development status and scope')} ↗</a></div></div></details>`;}
function sectionTitle(lang,n,title,desc){return `<div class="section-heading"><div><span class="index">${n}</span><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div></div>`;}
function buildHome(lang){const ko=lang==='ko',pre=ko?'../':'';const L=(k,e)=>t(lang,k,e);const nav=[['overview',L('모형 소개','Overview')],['capabilities',L('주요 기능','Capabilities')],['results',L('결과 해석','Results')],['programs',L('프로그램','Programs')],['research',L('연구·자료','Research')],['download',L('다운로드','Download')]];
 let html=head(lang,L('K-DRUM | 분포형 강우유출·하천수리·홍수해석','K-DRUM | Distributed hydrology, river hydraulics and flood analysis'),L('K-water의 격자단위 분포형 강우유출모형 K-DRUM. 확립된 수문 기능, 개발 중인 수리 확장, 공개 연구와 시각자료를 확인하세요.','Explore K-water’s grid-based distributed hydrologic model: established hydrology, hydraulic extensions in development, public research and visual guides.'),ko?'ko/':'',true)+homeHeader(lang);
 html+=`<main id="main"><section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">${L('유역에서 하천까지, 물의 흐름을 이해하다','Understand water, from watershed to river')}</p><h1>K-DRUM</h1><p class="full-name">K-water Grid-based Distributed Rainfall rUnoff Model</p><p class="lead">${L('강우와 유역의 공간적 차이를 반영하는 분포형 수문모형.','Distributed hydrology that represents rainfall and the spatial differences of a watershed.')}</p><p class="support">${L('K-water가 개발한 물리 기반 격자단위 강우유출모형입니다. 강우·침투·저류·유출을 연결하는 수문 기능을 중심으로 하천수리와 홍수범람 해석을 확장하고 있습니다.','Developed by K-water, K-DRUM connects rainfall, infiltration, storage and runoff on computational grids. River hydraulics and floodplain analysis are active extensions of this hydrologic foundation.')}</p><div class="actions"><a class="button primary" href="#overview">${L('모형 살펴보기','Explore the model')}</a><a class="button" href="${download}">${L('MyWater 무료 다운로드','Free download · MyWater')} ↗</a></div><div class="brand-credit"><a href="https://www.kwater.or.kr/kiwe/main.do"><img src="${pre}assets/kwater-ci.png" alt="K-water" width="84" height="36"></a><span>${L('공개 연구에 기반한 수문모형','Hydrology grounded in public research')}</span></div></div><figure class="hero-image"><img src="${pre}assets/visuals/kdrum-watershed-hero-HQ.jpg" width="886" height="760" fetchpriority="high" alt="${L('유역 지형, 계산격자와 하천망을 함께 표현한 개념 이미지','Concept image of watershed terrain, computational grids and a river network')}"><figcaption>${L('모형 이해를 돕는 개념 이미지이며 실제 수치모의 결과가 아닙니다.','Concept image for model introduction; not a numerical simulation result.')}</figcaption></figure></div></section><nav class="site-nav" aria-label="${L('본문 탐색','Page sections')}"><div class="wrap">${nav.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}</div></nav>`;
 html+=`<section class="section" id="overview"><div class="wrap">${sectionTitle(lang,'01 · K-DRUM',L('같은 비에도, 유역의 반응은 다릅니다.','The same rain can produce a different response.'),L('강우의 위치, 지형, 토양과 저장상태를 격자별로 다루어 물의 이동을 해석합니다.','Rainfall location, terrain, soil and storage states shape the movement of water across computational cells.'))}<div class="intro-grid"><article class="intro-block">${badge('ESTABLISHED',lang)}<h3>${L('격자 수문과 유출 전달','Grid hydrology and runoff routing')}</h3><p>${L('공간 강우, 침투, 지표·지표하 유출과 운동파 흐름추적이 모형의 수문 기반을 이룹니다.','Spatial rainfall, infiltration, surface/subsurface runoff and kinematic-wave routing form the hydrologic foundation.')}</p></article><article class="intro-block">${badge('ESTABLISHED',lang)}<h3>${L('사상에서 연속 물수지까지','From events to continuous water balance')}</h3><p>${L('토양수분, 증발산과 적설·융설을 시간에 따라 연결해 연속적인 유역 상태를 다룹니다.','Connect soil water, evapotranspiration and snow storage/melt through time for continuous watershed simulation.')}</p></article><article class="intro-block">${badge('ACTIVE DEVELOPMENT',lang)}<h3>${L('하천수리와 홍수범람 확장','River and floodplain extensions')}</h3><p>${L('1D 하천망, 구조물, 1D–2D 교환과 범람 해석은 기능별 개발·검증 범위를 구분해 소개합니다.','1D networks, hydraulic structures, 1D–2D exchange and floodplain analysis have feature-specific development and validation boundaries.')}</p></article></div>${figure('model-workflow',lang,pre,L('확립된 수문 기반과 개발 중인 수리 확장을 구분한 전체 계산 흐름.','The calculation path distinguishes established hydrology from hydraulic extensions in development.'))}<div class="feature-reading"><div><h3>${L('한 격자에서의 물순환','Water movement within a cell')}</h3><p>${domain.hydrology[lang]}</p>${figure('grid-water-cycle',lang,pre,L('물의 저장과 이동을 구분한 개념도.','Concept diagram distinguishing water storage from transfers.'))}</div><div><h3>${L('관측자료에서 공간 강우로','From observations to spatial rainfall')}</h3><p>${domain.forcing[lang]}</p>${figure('rainfall-grid',lang,pre,L('자료 입력과 공간배분 과정을 설명하는 예시.','An illustration of input data and spatial allocation.'))}</div></div></div></section>`;
 html+=`<section class="section soft" id="capabilities"><div class="wrap">${sectionTitle(lang,'02 · CAPABILITIES',L('기능과 적용 범위를 함께 확인하세요.','Explore capabilities and their boundaries.'),L('공개 저장소 기준 기능 45개와 별도 개발 중인 1D 결과 뷰어를 소개합니다. 항목을 열면 자료·계산 과정과 현재 상태를 볼 수 있습니다.','Explore 45 repository-tracked capabilities and a separate 1D results viewer in development. Open an entry for its data, process and public status.'))}<div class="filters" id="feature-filters" hidden><label>${L('분야','Category')}<select id="feature-group"><option value="">${L('전체 분야','All categories')}</option>${data.groups.map(g=>`<option value="${g.id}">${esc(g[lang])}</option>`).join('')}</select></label><label>${L('기능 검색','Find a capability')}<input type="search" id="feature-search" placeholder="${L('예: 강우, 물수지, NetCDF','e.g. rainfall, water balance, NetCDF')}"></label></div><p id="feature-count" class="result-count" aria-live="polite">46 ${L('개 항목','entries')}</p><div class="capability-grid">${data.items.map(it=>capability(it,lang,pre)).join('\n')}</div><p class="no-results" id="no-results" hidden>${L('일치하는 항목이 없습니다. 검색어나 분야를 바꿔 주세요.','No matching entries. Try another query or category.')}</p><div class="note">${L('기술 상태 기준: 2026-08-21 공개 검토. “개발 단계 검증”은 제한된 조건의 개발 검증이며 모든 유역에서의 적용성이나 인증을 뜻하지 않습니다.','Technical status follows the August 21, 2026 public review. “Validated development” refers to controlled development conditions, not universal applicability or certification.')} <a href="${repo}DEVELOPMENT_STATUS.md">${L('전체 상태 기준','Full status reference')} ↗</a></div></div></section>`;
 html+=`<section class="section" id="results"><div class="wrap">${sectionTitle(lang,'03 · RESULTS',L('결과는 숫자와 공간을 함께 읽습니다.','Read results in time and space.'),L('아래는 실제 유역 계산값이 아닌 결과 해석용 개념도입니다. 계산 완료, 물수지 일관성, 관측 비교는 각각 확인해야 합니다.','These are conceptual guides, not results from a real basin. Run completion, water-balance consistency and observation comparisons require separate checks.'))}<div class="results-layout">${figure('read-results',lang,pre,L('수문곡선의 시간·유량 축과 물수지 항을 함께 읽는 방법.','Read the time/discharge axes alongside the terms of a water balance.'))}<div class="results-notes"><div><h3>${L('공간분포','Spatial patterns')}</h3><p>${L('강우·토양수분·유출의 분포를 같은 범위와 시간에서 비교합니다. 범람 관련 출력은 해당 수리 기능의 개발 범위를 함께 확인합니다.','Compare rainfall, soil water and runoff over the same domain and period. Interpret flood outputs within the development scope of the hydraulic function.')}</p></div><div><h3>${L('수문곡선','Hydrographs')}</h3><p>${L('관측과 계산의 단위·시간 간격을 맞춘 뒤 첨두, 발생 시점과 감수부를 구분해서 검토합니다.','Align units and time intervals before reviewing peaks, timing and recession behavior in observations and calculations.')}</p></div><div><h3>${L('물수지','Water balance')}</h3><p>${L('유입·유출·저장량 변화·손실의 정의와 집계 범위를 확인합니다. 실행 성공만으로 물수지나 예측 정확도를 판단하지 않습니다.','Check the definitions and accounting domain of inputs, outputs, storage and losses. Execution success alone establishes neither balance nor predictive accuracy.')}</p></div></div></div><div class="diagram-panel"><h3>${L('하천과 범람원, 연결되는 두 계산 영역','River and floodplain: two connected domains')}</h3>${badge('ACTIVE DEVELOPMENT',lang)}${figure('river-floodplain',lang,pre,L('하천–범람원 교환의 개념. 제어된 개발 검증과 실유역 적용성은 구분합니다.','Conceptual river–floodplain exchange. Controlled validation and basin applicability are distinct.'))}</div></div></section>`;
 const programIds=['inputstudio','viewer','channelbed','netcdf','estuary','river-viewer'];
 html+=`<section class="section soft" id="programs"><div class="wrap">${sectionTitle(lang,'04 · PROGRAMS',L('준비, 계산, 검토의 역할을 나눕니다.','Prepare, compute, review.'),domain.platform[lang])}${figure('program-workflow',lang,pre,L('프로그램의 역할과 데이터 교환 관계.','Program roles and the exchange of data.'))}<div class="program-grid"><article class="program"><h3>K-DRUM Core</h3>${badge('ESTABLISHED',lang)}<p>${L('확립된 분포형 수문과 운동파 추적을 중심으로 합니다. Core 안의 수리·범람 확장까지 모두 확립됐다는 의미는 아닙니다.','Built around established distributed hydrology and kinematic routing. This does not label every hydraulic or flood extension inside Core as established.')}</p></article>${programIds.map(id=>{const it=data.items.find(i=>i.id===id);return `<article class="program"><h3>${esc(it[lang])}</h3>${badge(it.s,lang)}<p>${esc(get(it,'sum',lang))}</p><p>${esc(get(it,'now',lang))}</p></article>`;}).join('')}</div></div></section>`;
 html+=`<section class="section" id="research"><div class="wrap">${sectionTitle(lang,'05 · RESEARCH',L('공개 연구에서 확인하는 활용 맥락.','Applications grounded in public research.'),L('논문의 대상·자료와 적용 범위를 함께 읽으면 어떤 질문에 모형을 활용했는지 이해할 수 있습니다.','Read each study’s data, setting and scope to understand the questions addressed with the model.'))}<div class="stories">${renderStories(lang)}</div><div class="resource-links"><a href="${repo}PUBLICATIONS.md">${L('전체 논문과 원문 출처','All publications and sources')} ↗</a><a href="${repo}CAPABILITIES.md">${L('기능 설명','Capabilities')} ↗</a><a href="${repo}MODEL_CARD.md">Model Card ↗</a><a href="${pre}media.html?lang=${lang}">${L('발표자료·영상·18개 기능 이미지','Presentation, video and 18 feature images')} ↗</a></div></div></section>`;
 html+=`<section class="section soft" id="download"><div class="wrap download-layout"><div>${sectionTitle(lang,'06 · GET STARTED',L('공식 배포 자료부터 확인하세요.','Start with the official distribution.'),L('MyWater에서 공개되는 K-DRUM 자료와 이용 안내를 확인할 수 있습니다.','Visit MyWater for published K-DRUM materials and distribution guidance.'))}<a class="button primary" href="${download}">${L('MyWater 무료 다운로드','Free download from MyWater')} ↗</a></div><div><h3>${L('이용 전 확인할 내용','Before using a package')}</h3><ol><li>${L('배포 페이지에서 버전과 동봉 문서, 이용 조건을 확인합니다.','Check the version, included documentation and usage terms on the distribution page.')}</li><li>${L('현재 홈페이지의 개발 기능이 다운로드 파일에 모두 포함돼 있다고 가정하지 않습니다.','Do not assume every development feature on this website is included in the downloadable package.')}</li><li>${L('대상 유역의 자료와 적용 조건, 기능별 검증 범위를 확인합니다.','Review basin data, application conditions and feature-specific validation scope.')}</li></ol><div class="resource-links"><a href="${pre}seo-kdrum.html">${L('모형 소개와 자주 묻는 질문','Model guide and FAQ')} ↗</a><a href="https://www.kwater.or.kr/kiwe/main.do">${L('K-water 연구원','K-water Research Institute')} ↗</a></div></div></div></section></main>`;
 return html+footer(lang,pre)+viewer(lang)+'</body></html>\n';
}
function renderStories(lang){if(!editorial)return `<article class="story"><h3>${t(lang,'공개 연구 목록','Public research records')}</h3><p>${t(lang,'레이더 강우, 장기 융설과 지표수·지하수 연계 연구의 원문을 확인하세요.','Read the original studies on radar rainfall, snowmelt and surface/groundwater integration.')}</p><a href="${repo}PUBLICATIONS.md">${t(lang,'논문 목록','Publications')} ↗</a></article>`;return editorial.stories.map(st=>{const s=st[lang];return `<article class="story"><p class="eyebrow">${esc(st.year)}</p><h3>${esc(s.title)}</h3><p><strong>${esc(s.question)}</strong></p><p>${esc(s.context)}</p><p>${esc(s.method)}</p><p class="scope">${esc(s.scope)}</p><p class="citation"><a href="${esc(st.link)}">${esc(st.paperTitle)} ↗</a></p></article>`;}).join('');}
for(const lang of ['en','ko'])fs.writeFileSync(path.join(docs,lang==='en'?'index.html':'ko/index.html'),buildHome(lang));
function buildMedia(){const m=data.media;const asset='media/2026-09-12-p18/';const translated=(key)=>['ko','en'].map(lang=>`<span data-language="${lang}" ${lang==='en'?'hidden':''}>${esc(m.txt[lang][key])}</span>`).join('');
 const mediaHeader=`<header class="site-header"><div class="wrap header-row"><a class="brand" data-media-home href="ko/"><img src="assets/kdrum-symbol.png" width="36" height="36" alt="">K-DRUM</a><nav class="media-toolbar" aria-label="Language"><a href="?lang=ko" data-media-lang="ko" lang="ko" aria-current="page">한국어</a><a href="?lang=en" data-media-lang="en" lang="en">English</a></nav></div></header>`;
 let h=head('ko','K-DRUM 시각자료 | p18 공개 갤러리',m.txt.ko.intro,'media.html')+mediaHeader;
 h+=`<main id="main" data-media-page><div class="wrap"><div class="page-title"><p class="eyebrow">VISUAL GUIDE · P18</p><h1>${translated('title')}</h1><p>${translated('intro')}</p></div><div class="video-layout"><video controls playsinline preload="metadata" poster="${asset}07_Digital_Reference.png"><source src="${asset}KDRUM_Nature_to_Digital_22s_web.mp4" type="video/mp4"></video><div><h2>${translated('videoTitle')}</h2><p id="videoText">${translated('videoText')}</p><div class="actions"><a id="pdfBtn" class="button primary" href="${asset}K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${translated('pdf')} ↗</a><a class="button" href="${asset}KDRUM_Nature_to_Digital_22s_web.mp4">${translated('video')} ↗</a></div></div></div><div class="note">${translated('note')} <a href="${repo}DEVELOPMENT_STATUS.md">DEVELOPMENT_STATUS ↗</a> · <a href="${repo}CAPABILITIES.md">CAPABILITIES ↗</a></div>`;
 for(const lang of ['ko','en']){h+=`<div data-language="${lang}" lang="${lang}" id="gallery-${lang}" ${lang==='en'?'hidden':''}>`;for(const g of m.data){h+=`<section class="gallery-group"><h2>${g[0]} · ${esc(g[lang==='ko'?2:1])}</h2><div class="gallery-grid">`;for(const it of g[3]){const title=it[lang==='ko'?2:1],description=it[lang==='ko'?4:3],status=m.featureStatus[it[0]][lang==='ko'?1:0],src='assets/presentation/2026-09-12-p18/'+m.featureFiles[it[0]];h+=`<article class="media-card"><a href="${src}" data-enlarge data-caption="${esc(title+' · '+status)}" aria-label="${esc(title)} ${t(lang,'확대','— enlarge')}"><img class="thumb" src="${src}" alt="${esc(title)}" width="1600" height="900" loading="lazy" decoding="async"></a><div class="media-body"><span class="badge">${esc(status)}</span><h3>${esc(title)}</h3><p>${esc(description)}</p><a class="enlarge" href="${src}" data-enlarge data-caption="${esc(title+' · '+status)}">${t(lang,'이미지 확대','Enlarge image')} ↗</a></div></article>`;}h+='</div></section>';}h+='</div>';}
 h+=`<section class="gallery-group"><h2>${translated('resources')}</h2><div class="resource-links"><a href="${asset}K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${translated('rPdf')} ↗</a><a href="${asset}KDRUM_Nature_to_Digital_22s_web.mp4">${translated('rVideo')} ↗</a><a href="${asset}07_Digital_Reference.png">${translated('rImage')} ↗</a></div><p class="small">${translated('foot')}</p></section><noscript><p>이 페이지는 한국어로 제공됩니다. The Korean gallery and all original media links work without JavaScript; language switching requires JavaScript.</p></noscript></div></main>`;
 return h+`<div data-language="ko">${footer('ko')}</div><div data-language="en" hidden>${footer('en')}</div>`+viewer('ko')+'</body></html>\n';}
function buildGuide(){let h=head('ko','K-DRUM 모형 소개 · 자주 묻는 질문','K-water Grid-based Distributed Rainfall rUnoff Model의 입력·출력, 기능 상태, 공개 다운로드와 자료를 안내합니다.','seo-kdrum.html')+header('ko');h+=`<main id="main"><div class="wrap faq-layout"><div class="page-title"><p class="eyebrow">MODEL GUIDE</p><h1>K-DRUM 모형 소개</h1><p>K-water Grid-based Distributed Rainfall rUnoff Model</p><p>처음 접하는 분을 위한 모형의 범위, 자료와 이용 안내입니다. 확립된 수문 기능과 개발·연구 확장을 구분해 읽어 주세요.</p><div class="resource-links"><a href="ko/">한국어 홈페이지 ↗</a><a href="./" lang="en">English homepage ↗</a><a href="media.html?lang=ko">시각자료 ↗</a></div></div>`;
 for(const lang of ['ko','en']){h+=`<section class="section" lang="${lang}"><h2>${t(lang,'자주 묻는 질문','Frequently asked questions')}</h2>${(editorial?.faqs||[]).map(f=>`<details class="faq" ${lang==='ko'?'open':''}><summary>${esc(f[lang].question)}</summary><p>${esc(f[lang].answer)}</p></details>`).join('')}</section>`;}
 h+=`<div class="note">기능 상태 기준은 2026-08-21 공개 검토입니다. <a href="${repo}DEVELOPMENT_STATUS.md">DEVELOPMENT_STATUS</a> 및 <a href="${repo}MODEL_CARD.md">Model Card</a>를 함께 확인하세요.</div><section class="section"><h2>공개 자료</h2><div class="resource-links"><a href="${repo}PUBLICATIONS.md">논문과 출처 ↗</a><a href="${repo}CAPABILITIES.md">기능 설명 ↗</a><a href="${download}">MyWater 무료 배포 안내 ↗</a></div></section></div></main>`;
 const jsonld={'@context':'https://schema.org','@type':'SoftwareApplication',name:'K-DRUM',alternateName:'K-water Grid-based Distributed Rainfall rUnoff Model',applicationCategory:'ScientificApplication',description:'Physically based grid-distributed hydrologic model developed by K-water, with hydraulic extensions in development.',url:origin,publisher:{'@type':'Organization',name:'K-water'},sameAs:['https://github.com/YoungTeckHUR/KDRUM-Public']};
 // Preserve the existing SEO page social image; do not generate a new one.
 h=h.replace('</head>',`<meta property="og:title" content="K-DRUM | K-water 분포형 강우유출모형"><meta property="og:description" content="K-water의 물리 기반 격자형 분포형 수문모형 K-DRUM 공개 기술정보"><meta property="og:type" content="website"><meta property="og:url" content="${origin}seo-kdrum.html"><meta property="og:image" content="${origin}assets/visuals/kdrum-watershed-hero-HQ.jpg"><script type="application/ld+json">${JSON.stringify(jsonld)}</script></head>`);
 return h+footer('ko')+'</body></html>\n';}
fs.writeFileSync(path.join(docs,'media.html'),buildMedia());
fs.writeFileSync(path.join(docs,'seo-kdrum.html'),buildGuide());
module.exports={head,header,footer,viewer,figure,esc,t,origin,repo,docs,data};
