/* Static content first; site.js enhances these anchors into selected-content navigation. */
const references=require('./feature-reference-images.cjs');
const guidance=require('./capability-guidance.cjs');
const focused=require('./feature-specific-figures.cjs');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(l,k,e)=>l==='ko'?k:e;
const gallery={ga:'green-ampt-infiltration',runoff:'surface-subsurface-runoff',et:'evapotranspiration-soil-water',dlayer:'dlayer-delayed-baseflow'};
function asset(item,lang,pre=''){
 if(focused.get(item.id,lang,pre))return focused.get(item.id,lang,pre);
 if(references.concepts[item.id])return {...references.getReference(item.id,lang,pre),shared:false};
 if(gallery[item.id])return {src:pre+'assets/diagrams/grid-hydrology/'+gallery[item.id]+'-ko.webp',width:960,height:540,caption:item[lang],shared:false,koreanLabels:true};
 return null;
}
function validateAssets(data){
 const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
 for(const lang of ['ko','en']){
  const seen=new Map();
  for(const item of data.items){const pic=asset(item,lang);if(!pic)continue;
   const bytes=fs.readFileSync(path.join(__dirname,'../../docs',pic.src));
   const hash=crypto.createHash('sha256').update(bytes).digest('hex');
   if(seen.has(hash))throw Error('Repeated primary illustration: '+seen.get(hash)+' / '+item.id+' ('+lang+')');
   seen.set(hash,item.id);
  }
 }
}
function capability(item,lang,pre,{badge,data,repo,reading}){
 const L=(k,e)=>tr(lang,k,e),suffix=lang==='ko'?'Ko':'En',guide=guidance.get(item.id,lang),pic=asset(item,lang,pre);
 const scope=L('개념 설명용이며 실제 모의 결과나 프로그램 화면이 아닙니다.','Concept illustration, not a simulation result or software screenshot.');
 const caption=(focused.get(item.id,lang)?.caption||guide.figure)+(pic?.koreanLabels&&lang==='en'?' Image labels are in Korean.':'');
 const image=pic?`<figure class="figure feature-reference" data-reference-feature="${item.id}"><a class="feature-reference-image" href="${pic.src}" data-enlarge data-caption="${esc(caption+' '+scope)}" aria-label="${esc(L('그림 확대: ','Enlarge: ')+item[lang])}"><img src="${pic.src}" alt="${esc(caption)}" width="${pic.width}" height="${pic.height}" loading="lazy" decoding="async"></a><figcaption><strong>${pic.shared?L('공통 개념도에서 볼 부분','What to read in this shared illustration'):L('그림에서 볼 부분','What to read in the illustration')}</strong><span>${esc(caption)}</span><small>${scope}</small><a href="${pic.src}" data-enlarge data-caption="${esc(caption+' '+scope)}">${L('그림 크게 보기 ↗','Enlarge illustration ↗')}</a></figcaption></figure>`:(item.id==='wq'?`<p class="no-active-illustration">${esc(guide.figure)}</p>`:'');
 return `<details class="capability" id="cap-${item.id}" data-group="${item.g}" data-feature="${item.id}" data-search-terms="${esc(item.ko+' '+item.en+' '+item.id)}" data-status="${esc(item.s)}"><summary>${badge(item.s,lang)}<h3>${esc(item[lang])}</h3><p>${esc(item['sum'+suffix])}</p></summary><div class="cap-detail"><div class="feature-answer"><h4>${L('이 기능으로 판단할 것','What this helps you decide')}</h4><p>${esc(guide.goal)}</p></div>${image}<details class="technical-details"><summary>${L('상세 설명 · 입력과 계산 · 확인사항','Technical details · inputs · interpretation checks')}</summary><div class="detail-grid"><div><h4>${L('주요 입력 및 계산','Inputs and computation')}</h4><ol>${item['steps'+suffix].map((s,i)=>`<li><strong>${L(['입력·상태','처리·계산','결과·활용'][i],['Input / state','Processing','Output / use'][i])}</strong> — ${esc(s)}</li>`).join('')}</ol></div><div><h4>${L('작동 방식과 적용 범위','How it works and its scope')}</h4><p class="detail-overview">${esc(item['detail'+suffix])}</p></div></div><div class="interpretation-check"><h4>${L('결과를 읽을 때 확인할 점','Checks when interpreting results')}</h4><p>${esc(guide.check)}</p></div>${item['more'+suffix]?`<div class="note"><strong>${L('추가 설명','Further explanation')}</strong><p>${esc(item['more'+suffix])}</p>${item.conceptAnchor?`<a href="#${item.conceptAnchor}">${L('수문 개념도 모아보기','Hydrology concept gallery')} →</a>`:''}</div>`:''}<div class="detail-status"><h4>${L('개발 및 공개 상태','Development and availability')}</h4><p>${esc(item['now'+suffix])}</p></div><div class="resource-links"><a href="${repo}CAPABILITY_ATLAS.md">${L('기능별 공개 근거','Public capability reference')} ↗</a><a href="${repo}DEVELOPMENT_STATUS.md">${L('개발 상태와 범위','Development status and scope')} ↗</a></div></details><nav class="related-capabilities" aria-label="${L('함께 살펴볼 기능','Related capabilities')}"><strong>${L('함께 살펴보기','Explore next')}</strong>${guide.related.map(id=>`<a href="#cap-${id}">${esc(data.items.find(it=>it.id===id)[lang])} →</a>`).join('')}</nav>${!pic?references.referenceLinks(item,lang,pre):''}<div class="resource-links feature-tools"><a class="feature-share" href="#cap-${item.id}" data-share-feature="${item.id}">${L('이 기능 링크','Link to this capability')}</a><span class="feature-share-status" role="status"></span></div></div></details>`;
}
function sections(html){const out={};let depth=0,start=0,key;for(const m of html.matchAll(/<\/?section\b[^>]*>/g)){if(m[0].startsWith('</')){if(--depth===0)out[key]=html.slice(start,m.index+m[0].length);}else{if(depth++===0){start=m.index;key=/\bid="([^"]+)"/.exec(m[0])?.[1]||'hero';}}}if(depth!==0)throw Error('Unbalanced sections');return out;}
function compose(html,lang,{data}){
 guidance.validate(data);validateAssets(data);const L=(k,e)=>tr(lang,k,e),pre=lang==='ko'?'../':'',s=sections(html);
 const pages=[['home',L('홈','Home')],['capabilities',L('모형·기능','Model & capabilities')],['programs',L('프로그램','Programs')],['research',L('적용·연구','Research')],['download',L('자료·다운로드','Resources')]];
 const header=`<header class="site-header"><div class="wrap workspace-header"><a class="brand" href="#home"><img src="${pre}assets/kdrum-symbol.png" alt="" width="32" height="32">K-DRUM</a><nav class="workspace-nav" aria-label="${L('주 메뉴','Main navigation')}">${pages.map(([id,title])=>`<a href="#${id==='capabilities'?'overview':id}" data-page-link="${id}">${title}</a>`).join('')}</nav><div class="language"><a href="${pre||'./'}" lang="en" ${lang==='en'?'aria-current="page"':''}>English</a><a href="${pre}ko/" lang="ko" ${lang==='ko'?'aria-current="page"':''}>한국어</a></div></div></header>`;
 const topics=[['ga','01',L('유역 수문','Watershed hydrology'),L('비가 유출로 이어지는 과정','From rainfall to runoff'),L('공간 강우, 침투, 지표·지표하 유출과 흐름추적.','Spatial rainfall, infiltration, surface/subsurface runoff and routing.')],['continuous','02',L('연속 물순환','Continuous hydrology'),L('시간에 따라 변하는 유역 상태','Watershed states through time'),L('토양수분, 증발산, 적설·융설과 장기 물수지.','Soil water, evapotranspiration, snow and long-term water balance.')],['coupling','03',L('수리 확장 · 개발 중','Hydraulic extensions · in development'),L('하천에서 범람원까지','From river to floodplain'),L('하천망과 구조물, 하천–범람원 교환으로 확장.','Extensions to river networks, structures and river–floodplain exchange.')]];
 const intro=`<section class="wrap home-introduction" aria-labelledby="intro-materials-title"><figure><video controls playsinline preload="none" poster="${pre}media/2026-09-12-p18/07_Digital_Reference.png" aria-label="${L('K-DRUM 소개 영상','K-DRUM overview video')}"><source src="${pre}media/2026-09-12-p18/KDRUM_Nature_to_Digital_22s_web.mp4" type="video/mp4"><a href="${pre}media/2026-09-12-p18/KDRUM_Nature_to_Digital_22s_web.mp4">${L('영상 파일 열기','Open video file')}</a></video><figcaption>${L('소개 영상 · 22초 · AI 개념영상','Overview video · 22 seconds · AI concept visualization')}</figcaption></figure><div><h2 id="intro-materials-title">${L('K-DRUM 소개자료','Introducing K-DRUM')}</h2><p>${L('모형의 전체 구성과 주요 기능을 소개 영상, 발표자료와 18개 기능 이미지로 살펴보세요.','Explore the model and its capabilities through the overview video, presentation and 18 feature illustrations.')}</p><p class="small">${L('영상은 자연계의 물순환을 설명하는 개념영상이며 실제 수치모의 결과는 아닙니다.','The video illustrates watershed processes; it is not a numerical simulation result.')}</p><div class="actions"><a class="button primary intro-pdf" href="${pre}media/2026-09-12-p18/K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${L('소개 발표자료 PDF','Introduction PDF')} ↗</a><a class="button intro-gallery" href="${pre}media.html?lang=${lang}">${L('영상·전체 소개자료','Video & visual guide')} →</a></div><a class="small" href="${pre}media.html?lang=${lang}#review-notes">${L('소개자료 보완 안내 · 2026-09-20','Scope notes · 2026-09-20')} ↗</a> · <a class="intro-overview" href="#overview">${L('모형 전체 개요 읽기','Read the model overview')} →</a></div></section>`;
 const home=`<div id="home" data-workspace-page="home"><section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">K-WATER · DISTRIBUTED HYDROLOGY</p><h1>${L('유역의 물순환을 읽고,<br>물의 흐름을 연결합니다.','Understand watershed hydrology.<br>Connect the flow of water.')}</h1><p class="lead">${L('분포형 강우–유출모형 K-DRUM','K-DRUM distributed rainfall–runoff model')}</p><p class="support">${L('강우와 지형, 토양의 공간적 차이를 반영해 유역의 저장과 유출을 해석합니다.','Represent the spatial differences of rainfall, terrain and soils to examine watershed storage and runoff.')}</p><div class="actions"><a class="button primary" href="#overview">${L('모형과 기능 살펴보기','Explore the model')} →</a><a class="button" href="#download">${L('자료·다운로드','Resources')}</a></div></div><figure class="hero-image"><img src="${pre}assets/visuals/kdrum-watershed-hero-HQ.jpg" width="886" height="760" fetchpriority="high" alt="${L('유역 지형과 계산격자, 하천망을 나타낸 K-DRUM 개념 이미지','K-DRUM concept image of watershed terrain, computational cells and rivers')}"><figcaption>${L('유역과 계산격자의 연결을 표현한 개념 이미지','Concept image connecting the watershed and computational grid')}</figcaption></figure></div></section>${intro}<div class="wrap home-topics">${topics.map(([id,no,title,h,p])=>`<article><span class="eyebrow">${no} · ${title}</span><h2>${h}</h2><p>${p}</p><a href="#cap-${id}">${L('기능 살펴보기','Explore this topic')} →</a></article>`).join('')}</div><div class="wrap home-research"><div><strong>${L('연구와 적용 사례','Research and applications')}</strong><p>${L('공개 논문에서 모형의 활용과 적용 범위를 확인하세요.','Explore model applications and their scope in public studies.')}</p></div><a href="#research">${L('적용·연구 보기','Explore research')} →</a></div></div>`;
 const menu=`<details class="workspace-menu" open><summary>${L('목차 · 기능 선택','Contents · choose a capability')}</summary><aside class="workspace-sidebar" aria-label="${L('모형과 기능 목차','Model and capability contents')}"><a href="#overview" class="model-overview-link">${L('모형 개요','Model overview')}</a><div class="workspace-search" hidden><label for="feature-search">${L('기능 검색','Find a capability')}</label><input id="feature-search" type="search" placeholder="${L('예: 강우, 물수지','e.g. rainfall, balance')}"><p id="feature-count" role="status"></p><button type="button" id="feature-reset">${L('검색 초기화','Clear search')}</button></div><nav aria-label="${L('분야별 기능','Capabilities by category')}">${data.groups.map(g=>`<details class="feature-group" data-group="${g.id}" ${g.id==='hydrology'?'open':''}><summary>${esc(g[lang])}</summary><div>${data.items.filter(it=>it.g===g.id).map(it=>`<a href="#cap-${it.id}" data-feature-link="${it.id}">${esc(it[lang])}</a>`).join('')}</div></details>`).join('')}</nav><p id="no-results" hidden>${L('검색 결과가 없습니다. 다른 단어로 찾아보세요.','No matching capabilities. Try another term.')}</p><div class="workspace-reading"><a href="#results">${L('결과 해석 안내','Reading model results')}</a><a href="#grid-hydrology-concepts">${L('수문 개념도','Hydrology illustrations')}</a></div></aside></details>`;
 const capabilities=`<section id="capabilities" class="section" data-model-view><h2 class="capabilities-heading">${L('모형·기능','Model & capabilities')}</h2><p class="capabilities-intro">${L('목차에서 기능을 선택해 활용 목적, 그림과 확인사항을 살펴보세요.','Choose a capability to explore its purpose, illustration and interpretation checks.')}</p><div class="capability-grid">${s.capabilities.match(/<div class="capability-grid">([\s\S]*?)<\/div><p class="no-results"/)[1]}</div></section>`;
 const starts=[['rain-spatial',L('강우에서 유출까지','From rainfall to runoff'),L('강우 입력과 침투·유출 생성 과정을 따라갑니다.','Follow rainfall inputs, infiltration and runoff generation.')],['continuous',L('장기 물순환 이해','Understanding long-term hydrology'),L('계절별 저장 변화와 증발산·물수지를 살펴봅니다.','Explore seasonal storage, evapotranspiration and water balance.')],['coupling',L('하천·범람원 확장 검토','Exploring river–floodplain extensions'),L('하천과 범람원의 연결 및 개발 범위를 확인합니다.','Review river–floodplain connections and development scope.')],['input-precheck',L('계산 준비와 결과 확인','Preparing and reviewing a run'),L('입력 점검에서 출력 정합성과 결과 해석으로 이어갑니다.','Start with input checks, then explore output integrity and interpretation.')]];
 const startGuide=`<nav class="start-guide" aria-labelledby="start-guide-title"><h3 id="start-guide-title">${L('무엇부터 살펴볼까요?','Where would you like to start?')}</h3><div>${starts.map(([id,title,description])=>`<a href="#cap-${id}"><strong>${title} →</strong><span>${description}</span></a>`).join('')}</div></nav>`;
 const overview=s.overview.replace('<div class="intro-grid">',startGuide+'<div class="intro-grid">').replace('<div class="feature-reading">',`<details class="overview-depth"><summary>${L('격자 수문·강우 입력 자세히 보기','Explore cell hydrology and rainfall inputs')}</summary><div class="feature-reading">`).replace('<nav class="quick-entry"','</details><nav class="quick-entry"');
 const model=`<div class="wrap model-workspace" data-workspace-page="model">${menu}<div class="model-content"><p class="model-location" aria-live="polite"></p>${[overview,s['grid-hydrology-concepts'],capabilities,s.results].map(v=>v.includes('data-model-view')?v:v.replace('<section ','<section data-model-view ')).join('')}<nav class="model-next" aria-label="${L('다음 안내','Next steps')}"><a href="#results">${L('결과 해석 안내','Reading model results')} →</a><a href="#download">${L('자료와 이용 안내','Resources and access')} →</a></nav></div></div>`;
 let programs=s.programs;for(const it of data.items.filter(i=>['inputstudio','viewer','channelbed','netcdf','estuary','river-viewer'].includes(i.id))){const mark=`<h3>${esc(it[lang])}</h3>`;programs=programs.replace(mark,`<h3><a href="#cap-${it.id}">${esc(it[lang])}</a></h3>`);}
 let resources=s.download.replace('<h2>'+L('공식 배포와 이용 조건','Official distribution and terms of use')+'</h2>','<h2>'+L('자료·다운로드','Resources and downloads')+'</h2>');
 resources=resources.replace('</ol><div class="resource-links">',`</ol><div class="resource-links"><a href="${pre}media.html?lang=${lang}">${L('발표자료·영상·이미지','Presentation, video and images')} ↗</a>`);
 const start=html.slice(0,html.indexOf('<header class="site-header">')).replace('<body>','<body data-navigation-layout="workspace">');
 const end=html.slice(html.indexOf('</main>')+7);
 return start+header+'<main id="main">'+home+model+programs.replace('<section ','<section data-workspace-page="programs" ')+s.research.replace('<section ','<section data-workspace-page="research" ')+resources.replace('<section ','<section data-workspace-page="download" ')+'</main>'+end;
}
module.exports={capability,compose,asset,validateAssets};
