/* Static content first; site.js enhances these anchors into selected-content navigation. */
const references=require('./feature-reference-images.cjs');
const guidance=require('./capability-guidance.cjs');
const focused=require('./feature-specific-figures.cjs');
const useCases=require('./feature-use-cases.cjs');
const numerical=require('./numerical-guide.cjs');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(l,k,e)=>l==='ko'?k:e;
const gallery={ga:'green-ampt-infiltration',runoff:'surface-subsurface-runoff',et:'evapotranspiration-soil-water',dlayer:'dlayer-delayed-baseflow'};
function asset(item,lang,pre=''){
 if(focused.get(item.id,lang,pre))return focused.get(item.id,lang,pre);
 if(references.concepts[item.id])return {...references.getReference(item.id,lang,pre),shared:false};
 if(gallery[item.id])return {src:pre+'assets/diagrams/grid-hydrology/'+gallery[item.id]+'-ko.webp',width:960,height:540,caption:item[lang],shared:false,koreanLabels:true};
 return null;
}
function validateAssets(data){
 const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
 for(const lang of ['ko','en']){
  const seen=new Map();
  for(const item of data.items){const pic=asset(item,lang);if(!pic)continue;
   const bytes=fs.readFileSync(path.join(__dirname,'../../docs',pic.src));
   const hash=crypto.createHash('sha256').update(bytes).digest('hex');
   if(seen.has(hash))throw Error('Repeated primary illustration: '+seen.get(hash)+' / '+item.id+' ('+lang+')');
   seen.set(hash,item.id);
  }
 }
}
function balanceReading(id,lang){
 if(id!=='wb')return '';
 const L=(k,e)=>tr(lang,k,e);
 const rows=[
  [L('유입','Inputs'),L('강우와 외부에서 들어온 물','Rainfall and external inflows'),L('분석 영역이 받은 전체 물의 양','Total water entering the accounting domain')],
  [L('유출·손실','Outputs and losses'),L('유출·증발산·영역 밖으로 나간 손실','Outflow, evapotranspiration and losses leaving the domain'),L('경계를 나간 항만 합산하고 내부 이동은 구분','Count boundary outputs separately from internal transfers')],
  [L('저장 변화','Storage change'),L('종료 저장량 − 시작 저장량','Final storage minus initial storage'),L('토양·하천 등에 남거나 방출된 물','Water retained in or released from soil, channels and other stores')]
 ];
 return `<div class="balance-reading"><h4>${L('물수지 결과를 읽는 순서','Reading a water-balance result')}</h4><p>${L('먼저 기간과 계산 영역을 정한 뒤, 누적량을 같은 단위로 맞춥니다. 유량(m³/s)은 시간에 대해 적분해 체적(m³)으로, 수심(mm)은 해당 면적으로 환산해야 비교할 수 있습니다.','Choose a period and accounting domain, then use consistent units for accumulated quantities. Integrate discharge (m³/s) over time to obtain volume (m³); convert depths (mm) using the corresponding area.')}</p><table><caption>${L('집계 항목과 읽는 의미','Accounting terms and their meaning')}</caption><thead><tr><th scope="col">${L('항목','Term')}</th><th scope="col">${L('포함 내용','Contents')}</th><th scope="col">${L('해석','Interpretation')}</th></tr></thead><tbody>${rows.map(row=>`<tr><th scope="row">${row[0]}</th><td>${row[1]}</td><td>${row[2]}</td></tr>`).join('')}</tbody></table><p class="balance-equation">${L('잔차 = 누적 유입 − 누적 유출·손실 − 저장 변화','Residual = accumulated inputs − accumulated outputs and losses − storage change')}</p><p class="small">${L('수지를 읽기 위한 공통 정의입니다. 실제 리포트의 포함 항목과 부호를 먼저 확인합니다. 상대오차(%)는 분모가 강우량인지 총유입량인지에 따라 의미가 달라집니다.','This is a general accounting definition. First check the terms and sign convention in the actual report. Relative error (%) depends on whether its denominator is rainfall, total inflow or another reference.')}</p><h4>${L('이 정보로 무엇을 판단하나요?','What can this help you understand?')}</h4><ul><li>${L('유출량이 작을 때: 증발산으로 나간 물과 토양·하천에 남은 물을 나누어 원인을 해석합니다.','For low outflow, distinguish water lost through evapotranspiration from water remaining in soil and channel storage.')}</li><li>${L('잔차가 클 때: 전체 수지에서 사면·하천 및 저장층 사이의 전달로 범위를 좁혀, 집계 누락이나 중복 가능성을 점검합니다.','For a large residual, narrow the review from the overall balance to hillslope, channel and storage-layer transfers to investigate omitted or double-counted terms.')}</li><li>${L('연계 해석을 볼 때: 하천에서 빠진 교환량과 범람원에 들어간 교환량을 같은 기간으로 대응시킵니다.','For coupled analysis, match water transferred out of the river with water received by the floodplain over the same period.')} <a href="#cap-wb-1d2d">${L('1D–2D 교환 물수지 보기','Explore 1D–2D exchange balance')} →</a></li></ul></div>`;
}
function capability(item,lang,pre,{badge,data,repo,reading}){
 const L=(k,e)=>tr(lang,k,e),suffix=lang==='ko'?'Ko':'En',guide=guidance.get(item.id,lang),pic=asset(item,lang,pre);
 const scope=L('개념 설명용이며 실제 모의 결과나 프로그램 화면이 아닙니다.','Concept illustration, not a simulation result or software screenshot.');
 const caption=(focused.get(item.id,lang)?.caption||guide.figure)+(pic?.koreanLabels&&lang==='en'?' Image labels are in Korean.':'');
 const image=pic?`<figure class="figure feature-reference" data-reference-feature="${item.id}"><a class="feature-reference-image" href="${pic.src}" data-enlarge data-caption="${esc(caption+' '+scope)}" aria-label="${esc(L('그림 확대: ','Enlarge: ')+item[lang])}"><img src="${pic.src}" alt="${esc(caption)}" width="${pic.width}" height="${pic.height}" loading="lazy" decoding="async"></a><figcaption><small>${L('개념도 · 실제 계산 결과나 프로그램 화면이 아닙니다.','Concept illustration · not model output or a software screenshot.')}${pic.koreanLabels&&lang==='en'?' Korean labels.':''}</small><a href="${pic.src}" data-enlarge data-caption="${esc(caption+' '+scope)}">${L('확대해서 보기 ↗','Enlarge ↗')}</a></figcaption></figure>`:(item.id==='wq'?`<p class="no-active-illustration">${L('현재 빌드에서는 수질 계산이 비활성 상태입니다.','Water-quality calculations are disabled in the current build.')}</p>`:'');
 return `<details class="capability" id="cap-${item.id}" data-group="${item.g}" data-feature="${item.id}" data-search-terms="${esc(item.ko+' '+item.en+' '+item.id+' '+(item.searchTerms||''))}" data-status="${esc(item.s)}"><summary>${badge(item.s,lang)}<h3>${esc(item[lang])}</h3><p>${esc(useCases.get(item.id,lang))}</p></summary><div class="cap-detail"><div class="feature-answer"><h4>${L('얻을 수 있는 것','What you gain')}</h4><p>${esc(guide.goal)}</p></div>${image}<details class="technical-details"><summary>${pic?L('작동 방식·그림 해설·확인사항','How it works · figure guide · checks'):L('작동 방식·적용 범위·확인사항','How it works · scope · checks')}</summary>${pic?`<div class="figure-reading"><h4>${L('그림에서 볼 부분','Reading the illustration')}</h4><p>${esc(caption)}</p></div>`:''}<div class="detail-grid"><div><h4>${L('주요 입력 및 계산','Inputs and computation')}</h4><ol>${item['steps'+suffix].map((s,i)=>`<li><strong>${L(['입력·상태','처리·계산','결과·활용'][i],['Input / state','Processing','Output / use'][i])}</strong> — ${esc(s)}</li>`).join('')}</ol></div><div><h4>${L('작동 방식과 적용 범위','How it works and its scope')}</h4><p class="detail-overview">${esc(item['detail'+suffix])}</p></div></div>${numerical.feature(item,lang)}${balanceReading(item.id,lang)}<div class="interpretation-check"><h4>${L('결과를 읽을 때 확인할 점','Checks when interpreting results')}</h4><p>${esc(guide.check)}</p></div>${item['more'+suffix]?`<div class="note"><strong>${L('추가 설명','Further explanation')}</strong><p>${esc(item['more'+suffix])}</p>${item.conceptAnchor?`<a href="#${item.conceptAnchor}">${L('수문 개념도 모아보기','Hydrology concept gallery')} →</a>`:''}</div>`:''}<div class="detail-status"><h4>${L('개발 및 공개 상태','Development and availability')}</h4><p>${esc(item['now'+suffix])}</p></div><div class="resource-links"><a href="${repo}CAPABILITY_ATLAS.md">${L('기능별 공개 근거','Public capability reference')} ↗</a><a href="${repo}DEVELOPMENT_STATUS.md">${L('개발 상태와 범위','Development status and scope')} ↗</a></div>${!pic?references.referenceLinks(item,lang,pre):''}</details><nav class="related-capabilities" aria-label="${L('함께 살펴볼 기능','Related capabilities')}"><strong>${L('함께 살펴보기','Explore next')}</strong>${guide.related.map(id=>`<a href="#cap-${id}">${esc(data.items.find(it=>it.id===id)[lang])} →</a>`).join('')}</nav><div class="resource-links feature-tools"><a class="feature-share" href="#cap-${item.id}" data-share-feature="${item.id}">${L('이 기능 링크','Link to this capability')}</a><span class="feature-share-status" role="status"></span></div></div></details>`;
}
function sections(html){const out={};let depth=0,start=0,key;for(const m of html.matchAll(/<\/?section\b[^>]*>/g)){if(m[0].startsWith('</')){if(--depth===0)out[key]=html.slice(start,m.index+m[0].length);}else{if(depth++===0){start=m.index;key=/\bid="([^"]+)"/.exec(m[0])?.[1]||'hero';}}}if(depth!==0)throw Error('Unbalanced sections');return out;}
function compose(html,lang,{data}){
 guidance.validate(data);useCases.validate(data);validateAssets(data);const L=(k,e)=>tr(lang,k,e),pre=lang==='ko'?'../':'',s=sections(html);
 const pages=[['home',L('홈','Home')],['capabilities',L('모형·기능','Model & capabilities')],['programs',L('프로그램','Programs')],['research',L('적용·연구','Research')],['download',L('자료·다운로드','Resources')]];
 const header=`<header class="site-header"><div class="wrap workspace-header"><a class="brand" href="#home"><img src="${pre}assets/kdrum-symbol.png" alt="" width="32" height="32">K-DRUM</a><nav class="workspace-nav" aria-label="${L('주 메뉴','Main navigation')}">${pages.map(([id,title])=>`<a href="#${id==='capabilities'?'overview':id}" data-page-link="${id}">${title}</a>`).join('')}</nav><div class="language"><a href="${pre||'./'}" lang="en" ${lang==='en'?'aria-current="page"':''}>English</a><a href="${pre}ko/" lang="ko" ${lang==='ko'?'aria-current="page"':''}>한국어</a></div></div></header>`;
 const topics=[
 ['ga','01',L('유역 수문','Watershed hydrology'),L('비가 유출로 이어지는 과정','From rainfall to runoff'),L('공간 강우, 침투, 토양수분과 지표·지표하 유출이 어떻게 연결되는지 살펴봅니다.','Follow spatial rainfall, infiltration, soil water and surface/subsurface runoff.')],
 ['wb','02',L('연속 물순환·물수지','Continuous hydrology & water balance'),L('들어온 물이 어디에 머물고 어디로 나가는가','Where water is stored and where it leaves'),L('강우·증발산·유출·토양·적설·심부저류를 하나의 물수지로 연결해 계산의 일관성을 확인합니다.','Connect rainfall, evapotranspiration, runoff, soil, snow and deep storage in one water account.')],
 ['coupling','03',L('하천수리·홍수범람','River hydraulics & flooding'),L('하천에서 범람원까지','From river to floodplain'),L('1D 하천수리, 구조물, 1D–2D 교환과 2D 범람 해석의 역할을 구분해 살펴봅니다.','Explore the distinct roles of 1D river hydraulics, structures, 1D–2D exchange and 2D flooding.')],
 ['inputstudio','04',L('입력·결과분석 환경','Input & result workflow'),L('입력자료 작성부터 결과 해석까지','From input authoring to result interpretation'),L('InputStudio, NetCDF와 Viewer가 계산 전 준비·실행·결과분석을 어떻게 연결하는지 살펴봅니다.','See how InputStudio, NetCDF and viewers connect preparation, execution and result analysis.')]
];
 const intro=`<section class="wrap home-introduction" aria-labelledby="intro-materials-title"><figure><video controls playsinline preload="none" poster="${pre}media/2026-09-12-p18/07_Digital_Reference.png" aria-label="${L('K-DRUM 소개 영상','K-DRUM overview video')}"><source src="${pre}media/2026-09-12-p18/KDRUM_Nature_to_Digital_22s_web.mp4" type="video/mp4"><a href="${pre}media/2026-09-12-p18/KDRUM_Nature_to_Digital_22s_web.mp4">${L('영상 파일 열기','Open video file')}</a></video><figcaption>${L('소개 영상 · 22초 · AI 개념영상','Overview video · 22 seconds · AI concept visualization')}</figcaption></figure><div><h2 id="intro-materials-title">${L('K-DRUM 소개자료','Introducing K-DRUM')}</h2><p>${L('모형의 전체 구성과 주요 기능을 소개 영상, 발표자료와 18개 기능 이미지로 살펴보세요.','Explore the model and its capabilities through the overview video, presentation and 18 feature illustrations.')}</p><p class="small">${L('영상은 자연계의 물순환을 설명하는 개념영상이며 실제 수치모의 결과는 아닙니다.','The video illustrates watershed processes; it is not a numerical simulation result.')}</p><div class="actions"><a class="button primary intro-pdf" href="${pre}media/2026-09-12-p18/K-DRUM_v3.x_p18.pdf" target="_blank" rel="noopener">${L('소개 발표자료 PDF','Introduction PDF')} ↗</a><a class="button intro-gallery" href="${pre}media.html?lang=${lang}">${L('영상·전체 소개자료','Video & visual guide')} →</a></div><a class="small" href="${pre}media.html?lang=${lang}#review-notes">${L('소개자료 보완 안내 · 2026-09-20','Scope notes · 2026-09-20')} ↗</a> · <a class="intro-overview" href="#overview">${L('모형 전체 개요 읽기','Read the model overview')} →</a></div></section>`;
 const home=`<div id="home" data-workspace-page="home"><section class="hero"><div class="wrap hero-grid"><div><p class="eyebrow">K-WATER · DISTRIBUTED HYDROLOGY</p><h1>${L('유역의 물순환을 읽고,<br>물의 흐름을 연결합니다.','Understand watershed hydrology.<br>Connect the flow of water.')}</h1><p class="lead">${L('분포형 강우–유출모형 K-DRUM','K-DRUM distributed rainfall–runoff model')}</p><p class="support">${L('강우와 지형, 토양의 공간적 차이를 반영해 유역의 저장과 유출을 해석합니다.','Represent the spatial differences of rainfall, terrain and soils to examine watershed storage and runoff.')}</p><div class="actions"><a class="button primary" href="#overview">${L('모형과 기능 살펴보기','Explore the model')} →</a><a class="button" href="#download">${L('자료·다운로드','Resources')}</a></div></div><figure class="hero-image"><img src="${pre}assets/visuals/kdrum-watershed-hero-HQ.jpg" width="886" height="760" fetchpriority="high" alt="${L('유역 지형과 계산격자, 하천망을 나타낸 K-DRUM 개념 이미지','K-DRUM concept image of watershed terrain, computational cells and rivers')}"><figcaption>${L('유역과 계산격자의 연결을 표현한 개념 이미지','Concept image connecting the watershed and computational grid')}</figcaption></figure></div></section>${intro}<div class="wrap home-topics">${topics.map(([id,no,title,h,p])=>`<article><span class="eyebrow">${no} · ${title}</span><h2>${h}</h2><p>${p}</p><a href="#cap-${id}">${L('기능 살펴보기','Explore this topic')} →</a></article>`).join('')}</div><div class="wrap home-research"><div><strong>${L('연구와 적용 사례','Research and applications')}</strong><p>${L('공개 논문에서 모형의 활용과 적용 범위를 확인하세요.','Explore model applications and their scope in public studies.')}</p></div><a href="#research">${L('적용·연구 보기','Explore research')} →</a></div></div>`;
 const menu=`<details class="workspace-menu" open><summary>${L('목차 · 기능 선택','Contents · choose a capability')}</summary><aside class="workspace-sidebar" aria-label="${L('모형과 기능 목차','Model and capability contents')}"><a href="#overview" class="model-overview-link">${L('모형 개요','Model overview')}</a><div class="workspace-search" hidden><label for="feature-search">${L('기능 검색','Find a capability')}</label><input id="feature-search" type="search" placeholder="${L('예: 강우, 물수지','e.g. rainfall, balance')}"><p id="feature-count" role="status"></p><button type="button" id="feature-reset">${L('검색 초기화','Clear search')}</button></div><nav aria-label="${L('분야별 기능','Capabilities by category')}">${data.groups.map(g=>`<details class="feature-group" data-group="${g.id}" ${g.id==='hydrology'?'open':''}><summary>${esc(g[lang])}</summary><div>${data.items.filter(it=>it.g===g.id).map(it=>`<a href="#cap-${it.id}" data-feature-link="${it.id}">${esc(it[lang])}</a>`).join('')}</div></details>`).join('')}</nav><p id="no-results" hidden>${L('검색 결과가 없습니다. 다른 단어로 찾아보세요.','No matching capabilities. Try another term.')}</p><div class="workspace-reading"><a href="#numerical-methods">${L('방정식·수치기법','Equations & numerics')}</a><a href="#results">${L('결과 해석 안내','Reading model results')}</a><a href="#grid-hydrology-concepts">${L('수문 개념도','Hydrology illustrations')}</a></div></aside></details>`;
 const capabilities=`<section id="capabilities" class="section" data-model-view><h2 class="capabilities-heading">${L('세부 기능','Detailed capabilities')}</h2><p class="capabilities-intro">${L('먼저 관심 분야를 고른 뒤, 각 기능에서 활용 목적 → 핵심 원리 → 그림 → 해석 시 확인사항 순서로 읽을 수 있습니다. 연구·실험 기능은 확립 기능과 구분해 표시합니다.','Choose an area first, then read each capability in the order purpose → mechanism → illustration → interpretation checks. Research and experimental functions are shown separately from established functions.')}</p><div class="capability-grid">${s.capabilities.match(/<div class="capability-grid">([\s\S]*?)<\/div><p class="no-results"/)[1]}</div></section>`;
 const starts=[
 ['rain-spatial',L('유역 수문 따라가기','Follow watershed hydrology'),L('공간 강우에서 침투·유출 생성과 흐름추적까지 이어서 봅니다.','Follow spatial rainfall through infiltration, runoff generation and routing.')],
 ['wb',L('물수지로 전체 흐름 보기','Read the whole system through water balance'),L('강우·저장·증발산·유출을 같은 기간과 단위로 연결해 봅니다.','Connect rainfall, storage, evapotranspiration and runoff over the same period and units.')],
 ['coupling',L('하천수리·범람 확장 보기','Explore river hydraulics and flooding'),L('1D 수리와 1D–2D·2D 기능의 역할과 개발 범위를 구분합니다.','Distinguish 1D hydraulics from 1D–2D and 2D functions and their development scope.')],
 ['inputstudio',L('입력부터 결과분석까지','From inputs to result analysis'),L('InputStudio, 출력 형식과 Viewer를 하나의 작업흐름으로 살펴봅니다.','Explore InputStudio, output formats and viewers as one workflow.')]
];
 const startGuide=`<nav class="start-guide" aria-labelledby="start-guide-title"><h3 id="start-guide-title">${L('무엇부터 살펴볼까요?','Where would you like to start?')}</h3><div>${starts.map(([id,title,description])=>`<a href="#cap-${id}"><strong>${title} →</strong><span>${description}</span></a>`).join('')}</div></nav>`;
 const overview=s.overview.replace('<div class="intro-grid">',startGuide+`<a class="numerical-entry" href="#numerical-methods"><strong>${L('운동파와 동역학파는 무엇이 다를까요?','How do kinematic and dynamic waves differ?')}</strong><span>${L('방정식의 항 · 계산 방법 · 해석 선택 기준','Equation terms · numerical methods · choosing an approach')} →</span></a><div class="intro-grid">`).replace('<div class="feature-reading">',`<details class="overview-depth"><summary>${L('격자 수문·강우 입력 자세히 보기','Explore cell hydrology and rainfall inputs')}</summary><div class="feature-reading">`).replace('<nav class="quick-entry"','</details><nav class="quick-entry"');
 const model=`<div class="wrap model-workspace" data-workspace-page="model">${menu}<div class="model-content"><p class="model-location" aria-live="polite"></p>${[overview,numerical.render(lang,pre),s['grid-hydrology-concepts'],capabilities,s.results].map(v=>v.includes('data-model-view')?v:v.replace('<section ','<section data-model-view ')).join('')}<nav class="model-next" aria-label="${L('다음 안내','Next steps')}"><a href="#results">${L('결과 해석 안내','Reading model results')} →</a><a href="#download">${L('자료와 이용 안내','Resources and access')} →</a></nav></div></div>`;
 let programs=s.programs;for(const it of data.items.filter(i=>['inputstudio','viewer','channelbed','netcdf','estuary','river-viewer'].includes(i.id))){const mark=`<h3>${esc(it[lang])}</h3>`;programs=programs.replace(mark,`<h3><a href="#cap-${it.id}">${esc(it[lang])}</a></h3>`);}
 let resources=s.download.replace('<h2>'+L('공식 배포와 이용 조건','Official distribution and terms of use')+'</h2>','<h2>'+L('자료·다운로드','Resources and downloads')+'</h2>');
 resources=resources.replace('</ol><div class="resource-links">',`</ol><div class="resource-links"><a href="${pre}media.html?lang=${lang}">${L('발표자료·영상·이미지','Presentation, video and images')} ↗</a>`);
 const start=html.slice(0,html.indexOf('<header class="site-header">')).replace('<body>','<body data-navigation-layout="workspace">');
 const end=html.slice(html.indexOf('</main>')+7);
 return start+header+'<main id="main">'+home+model+programs.replace('<section ','<section data-workspace-page="programs" ')+s.research.replace('<section ','<section data-workspace-page="research" ')+resources.replace('<section ','<section data-workspace-page="download" ')+'</main>'+end;
}
module.exports={capability,compose,asset,validateAssets};
