/* Public mathematical primer. General equations are not a dump of solver internals. */
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const depth=require('../../docs/assets/feature-depth.json');
const hydraulic=new Set(['kw-hill','kw-river','dwnet','junction','local-inertia','fullswe','coupling','multires']);
function feature(item,lang){const ko=lang==='ko',d=depth[item.id];if(!d)throw Error('Missing depth: '+item.id);return `<div class="feature-depth"><h4>${ko?'원리를 이해하기':'Understand the mechanism'}</h4><p>${esc(d[ko?'principleKo':'principleEn'])}</p><h4>${ko?'해석에 적용하기':'Apply it to interpretation'}</h4><p>${esc(d[ko?'exampleKo':'exampleEn'])}</p>${hydraulic.has(item.id)?`<a class="numerical-link" href="#numerical-methods">${ko?'방정식·수치기법·선택 기준 자세히 보기':'Explore equations, numerical methods and selection'} →</a>`:''}</div>`;}
function render(lang,pre){const L=(k,e)=>lang==='ko'?k:e,p=(k,e)=>`<p>${L(k,e)}</p>`,h=(k,e)=>`<h3>${L(k,e)}</h3>`,eq=(formula,k,e)=>`<div class="equation"><div class="formula" role="math" aria-label="${esc(L(k,e))}">${formula}</div><p>${L(k,e)}</p></div>`,detail=(id,k,e,body)=>`<details class="numerical-topic" id="${id}"><summary>${L(k,e)}</summary><div class="numerical-body">${body}</div></details>`;
const rows=[
 ['kw-river',L('운동파','Kinematic wave'),'—','—','—',L('중력 ≈ 마찰','Gravity ≈ friction'),L('유출 전달·도달시간','Runoff routing / travel time')],
 ['local-inertia',L('확산파','Diffusion wave'),'—','—','●',L('포함','Included'),L('완만한 수면경사 지배 흐름','Gradual, stage-gradient-driven flow')],
 ['local-inertia',L('국부관성','Local inertia'),'●','—','●',L('포함','Included'),L('이류 가속도가 작은 비정상 범람','Unsteady flooding with small advection')],
 ['fullswe',L('동역학파 / Full SWE','Dynamic wave / Full SWE'),'●','●','●',L('포함','Included'),L('운동량 변화·중력파 전파','Momentum changes / gravity waves')]
];
let out=`<section class="section numerical-guide" id="numerical-methods"><div class="wrap"><div class="section-heading"><div><span class="index">NUMERICAL METHODS</span><h2>${L('운동파에서 동역학파까지','From kinematic to dynamic waves')}</h2>${p('어떤 물리를 남기고, 그것을 격자와 시간단계에서 어떻게 계산하는지 이해합니다. 해석 목적에 맞는 방법을 고른 뒤 필요한 심화 항목을 펼쳐 보세요.','Understand which physics are retained and how they are computed over cells and time steps. Compare the approaches, then open the topics relevant to your analysis.')}</div></div>`;
out+=`<div class="method-distinction"><strong>${L('두 가지 선택을 구분합니다','Separate two choices')}</strong>${p('운동파·확산파·국부관성·동역학파는 지배방정식의 근사 수준입니다. 유한체적·차분, 양해·음해는 그 방정식을 계산하는 방법입니다. “동역학파이므로 음해법” 또는 “양해법이므로 운동파”가 되는 것은 아닙니다.','Kinematic, diffusion, local-inertial and dynamic waves describe equation approximations. Finite volumes/differences and explicit/implicit stepping describe numerical solution methods. Dynamic wave does not automatically mean implicit, nor explicit mean kinematic.')}</div>`;
out+=`<p class="small">${L('● 유지 · — 생략. 수심평균 수리방정식의 일반적인 비교이며, 아래 항목에서 K-DRUM의 경로를 구분합니다. 작은 화면에서는 표를 좌우로 움직일 수 있습니다.','● retained · — omitted. A general comparison of depth-averaged equations; K-DRUM paths are distinguished below. Scroll the table horizontally on small screens.')}</p><div class="method-table-scroll" tabindex="0" role="region" aria-label="${L('수리 근사별 운동량 항 비교','Momentum terms by hydraulic approximation')}"><table class="method-table"><caption>${L('어떤 운동량 항을 계산하는가','Which momentum terms are retained?')}</caption><thead><tr>${[L('근사','Approximation'),L('시간 가속도','Local acceleration'),L('이류 가속도','Advective acceleration'),L('수심경사','Depth gradient'),L('중력·마찰','Gravity / friction'),L('주요 해석 대상','Typical analysis')].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r[1]}</th>${r.slice(2).map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
out+=detail('numerical-equations','01 · 방정식과 각 항의 의미','01 · Equations and the meaning of each term',
 h('왜 천수방정식인가','Why shallow-water equations?')+p('“얕다”는 절대 수심이 작다는 뜻만이 아니라 수평 변화 길이에 비해 수심이 작다는 뜻입니다. 수직 가속도의 영향을 작게 보고 압력을 정수압으로 근사하며 수심 방향으로 평균합니다. 그래서 수심이 있는 하천에도 적용할 수 있지만, 낙하류·강한 수직 순환을 모두 재현하는 3차원 해석은 아닙니다.','Shallow refers to depth relative to the horizontal variation length, not just a small absolute depth. Depth averaging and a hydrostatic approximation reduce the role of vertical acceleration. Deep rivers can meet these assumptions; strongly vertical jets and circulation need additional treatment.')+
 eq('∂A/∂t + ∂Q/∂x = q<sub>l</sub>','1D 연속식: 단면적 A [m²], 유량 Q [m³/s], 단위 길이당 측방유입 qₗ [m²/s].','1D continuity: area A [m²], discharge Q [m³/s], lateral inflow per unit length qₗ [m²/s].')+
 eq('∂q/∂t + ∂(q²/h)/∂x + gh ∂h/∂x = gh(S<sub>0</sub> − S<sub>f</sub>)','일정 폭의 단순 수로에서 측방 운동량·추가 외력을 생략한 설명식. q = hu는 단위폭 유량 [m²/s], u는 유속, h는 수심, S₀는 하상경사, S_f는 부호를 갖는 마찰경사입니다.','Illustrative momentum equation for a simple constant-width channel, omitting lateral momentum and additional forces. q = hu is unit-width discharge [m²/s], u velocity, h depth, S₀ bed slope and S_f signed friction slope.')+
 `<dl class="term-definitions"><dt>∂q/∂t</dt><dd>${L('한 위치의 단위폭 유량이 시간에 따라 변하는 국부관성 항.','Local inertia: unit-width discharge changes over time at a location.')}</dd><dt>∂(q²/h)/∂x</dt><dd>${L('물이 빠른 구간이나 느린 구간으로 이동하며 겪는 이류 가속도.','Advective acceleration: water moves into a region with different velocity.')}</dd><dt>gh ∂h/∂x</dt><dd>${L('수심 차에 의한 압력경사. 하상경사와 합쳐 수면경사로 작용합니다.','Pressure gradient due to depth differences; together with bed slope it gives the water-surface gradient.')}</dd></dl>`+
 p('운동파는 가속도와 수심경사를 생략해 S_f ≈ S₀로 놓습니다. 확산파는 가속도를 생략하지만 수면경사를 남깁니다. 국부관성은 시간 가속도를 추가하고, 동역학파는 이류 가속도까지 다룹니다. 1D·2D는 공간 표현의 차원이므로 이 근사 수준과 별도로 구분합니다.','Kinematic flow uses S_f ≈ S₀. Diffusion wave retains the surface-gradient balance but drops accelerations. Local inertia restores temporal acceleration; dynamic wave also retains advection. Spatial dimension (1D/2D) is a separate choice.')+
 `<p class="small">${L('이론 참고','Theory references')}: <a href="https://www.hec.usace.army.mil/confluence/hmsdocs/hmstrm/channel-flow/kinematic-wave-channel-routing-model">USACE · Kinematic wave</a> · <a href="https://www.clawpack.org/riemann_book/html/Shallow_water.html">Clawpack · Shallow-water equations</a></p>`);
out+=detail('numerical-selection','02 · 어떤 상황에서 차이가 커지는가','02 · When do these differences matter?',
 `<div class="method-cases">${[
 [L('유역의 출구 유량과 도달시간','Outlet discharge and timing'),L('배수위 영향이 작고 흐름이 주로 경사를 따라 전달된다면 운동파가 출발점입니다. 상류에서 생성된 유출과 사면·하도의 전달시간을 분리해 봅니다.','With little backwater and predominantly slope-driven routing, kinematic wave is a useful starting point. Separate generated runoff from hillslope/channel travel time.'),'kw-river'],
 [L('완경사와 하류 수위 상승','Mild slopes and rising downstream stage'),L('수면경사가 하상경사와 달라지는 상황입니다. 확산파·국부관성·동역학파처럼 수면차를 다루는 접근이 필요하며, 변화가 빠를수록 가속도 항의 중요성을 검토합니다.','Water-surface and bed slopes can differ. Methods retaining surface gradients become relevant; faster changes increase the need to examine acceleration terms.'),'dwnet'],
 [L('완만한 범람 확산','Gradual inundation spreading'),L('이류 가속도가 작은 범람에서는 국부관성 근사의 계산 효율을 활용할 수 있습니다. 같은 지형과 경계조건에서 도달시간·수심·유량을 함께 비교합니다.','Local inertia can be efficient where advective acceleration is small. Compare arrival time, depth and flow under matching terrain and boundary conditions.'),'local-inertia'],
 [L('급격한 유입·수축·빠른 흐름','Abrupt inflow, contractions and fast flow'),L('이류와 파동 전파가 중요하면 Full SWE가 비교 대상입니다. 더 많은 항을 계산해도 부정확한 지형·경계조건이나 부족한 해상도를 자동으로 해결하지는 않습니다.','When advection and wave propagation matter, compare Full SWE. More complete equations do not automatically correct poor terrain, boundaries or inadequate resolution.'),'fullswe']
 ].map(([t,b,id])=>`<article><h3>${t}</h3><p>${b}</p><a href="#cap-${id}">${L('관련 K-DRUM 기능','Related K-DRUM capability')} →</a></article>`).join('')}</div>`+
 p('선택은 경사 하나로 결정하지 않습니다. 수심에 대한 유속의 크기, 변화 시간, 하류 수위 영향, 단면 변화와 관심 출력이 함께 중요합니다. 조위가 경계에 작용하는 하천과 강우 유출의 도달시간 문제는 요구하는 물리가 다릅니다.','Slope alone is insufficient. Relative velocity and depth, forcing timescale, downstream control, geometry changes and target outputs all matter. Tidal boundary effects and rainfall-runoff travel time pose different questions.'));
out+=detail('numerical-discretization','03 · 격자에서 유량과 저장을 계산하는 방법','03 · Computing fluxes and storage on a mesh',
 h('유한체적과 차분','Finite volumes and finite differences')+p('유한체적법은 셀 안의 보존량 변화를 경계로 들어오고 나간 플럭스로 계산합니다. 같은 경계 유량을 양쪽 셀이 공유하면 내부 이동은 전체 합계에서 상쇄됩니다. 유한차분법은 미분을 이웃 값의 차이로 근사하며, 보존형으로 구성할 수도 있습니다. 두 이름만으로 정확도 우열을 정할 수는 없습니다.','Finite volumes update a cell’s conserved amount from boundary fluxes. A shared interface flux cancels in the sum over neighboring cells. Finite differences approximate derivatives from neighboring values and can also be conservative; the names alone do not rank accuracy.')+
 `<figure class="figure"><a href="${pre}assets/diagrams/feature-specific/finite-volume-${lang}.svg" data-enlarge data-caption="${L('공유 경계의 유량과 셀별 저장량 갱신','Shared face discharge and cell-storage updates')}"><img src="${pre}assets/diagrams/feature-specific/finite-volume-${lang}.svg" width="1200" height="720" loading="lazy" alt="${L('세 셀의 경계 유량을 공유해 내부 교환이 상쇄되는 유한체적 개념도','Finite-volume concept: three cells share face discharges so internal exchanges cancel')}"></a><figcaption>${L('공통 수치 원리 도식 · 실제 계산 결과 아님 · 눌러서 확대','General numerical principle · not simulation output · click to enlarge')}</figcaption></figure>`+
 eq('V<sub>i</sub><sup>n+1</sup> = V<sub>i</sub><sup>n</sup> + Δt (Q<sub>in</sub> − Q<sub>out</sub> + Q<sub>source</sub>)','저장체적 V [m³]와 유량 Q [m³/s]의 보존형 갱신 예시. 여러 경계가 있으면 모든 경계 유량을 부호에 맞춰 합합니다.','Illustrative conservative update of volume V [m³] using discharge Q [m³/s]. Sum signed flows over all faces when a cell has multiple boundaries.')+
 p('물수지만 맞춘다고 운동량 해석까지 같아지지는 않습니다. 운동파는 흐름–저장 관계로 유량을 닫고, 국부관성은 이전 유량과 수면차를 사용하며, Full SWE는 질량뿐 아니라 운동량 플럭스도 갱신합니다.','Mass conservation alone does not make momentum representations equivalent. Kinematic routing closes discharge with a storage relation; local inertia uses previous flow and surface gradients; Full SWE also updates momentum fluxes.')+
 h('해상도와 수치 확산','Resolution and numerical diffusion')+p('셀 평균값을 경계로 복원하는 방법과 플럭스 계산은 급격한 변화가 얼마나 퍼져 보이는지에 영향을 줍니다. 고차 복원은 매끄러운 구간을 더 잘 표현할 수 있지만, 급변부에서는 진동을 억제하는 제한이 필요합니다. 격자를 줄인 결과가 계속 달라지면 해상도 수렴이 아직 확보되지 않은 것입니다.','Reconstruction and flux evaluation affect how strongly sharp changes are smeared. Higher-order reconstruction can improve smooth regions, while limiting is needed near abrupt changes. Continued change under refinement indicates that resolution convergence has not yet been established.'));
out+=detail('numerical-time','04 · 양해·음해·반음해와 시간간격','04 · Explicit, implicit and semi-implicit time stepping',
 p('양해법은 이미 알려진 상태로 다음 상태를 계산합니다. 음해법은 다음 시점의 미지수가 식 안에 들어가 연립 또는 비선형 문제를 풀어야 합니다. 반음해는 항에 따라 두 처리를 섞습니다. “음해”는 숨겨진 물리라는 뜻이 아니라 미지수의 평가 시점을 뜻합니다.','Explicit methods evaluate updates from known states. Implicit methods include new-time unknowns and require a coupled or nonlinear solve. Semi-implicit methods mix treatments across terms. These names describe time evaluation, not different physical processes.')+
 eq('(y<sup>n+1</sup> − y<sup>n</sup>)/Δt = f(y<sup>n</sup>)','전진 Euler: 양해 시간적분의 설명 예시.','Forward Euler: an illustrative explicit time step.')+
 eq('(y<sup>n+1</sup> − y<sup>n</sup>)/Δt = f(y<sup>n+1</sup>)','후진 Euler: 음해 시간적분의 설명 예시. 특정 K-DRUM 모드 전체를 이 식으로 단정하는 것은 아닙니다.','Backward Euler: an illustrative implicit time step, not a claim that every K-DRUM mode uses this formula.')+
 p('음해법도 큰 시간간격에서 첨두·위상을 흐리게 만들 수 있고 반복해의 수렴이 필요합니다. 양해법은 파동이 셀을 통과하는 속도와 시간간격의 관계가 중요합니다. 안정적으로 끝나는 것과 시간 변화가 충분히 정확한 것은 별개입니다.','Implicit stepping can still smear peaks and timing with large steps, and nonlinear iterations must converge. Explicit stepping must respect propagation relative to cell size. Stable completion does not establish temporal accuracy.')+
 eq('C = (|u| + √(gh)) Δt / Δx','단순 1D 천수파의 Courant 수 예시. 허용값은 수치기법에 따르며 2D 계산·생성/소멸항·경계조건은 추가 제약을 가질 수 있습니다.','Illustrative Courant number for 1D shallow-water waves. Limits depend on the method; 2D geometry, sources and boundaries may impose additional restrictions.')+
 p('시간간격을 줄여 주요 지점의 첨두·도달시간·물수지가 충분히 비슷해지는지 비교합니다. 강우 입력 간격, 엔진 내부 계산 간격, 결과 저장 간격은 서로 다를 수 있으므로 파일의 시각만 보고 내부 계산간격을 추정하지 않습니다.','Reduce the timestep and compare peak, arrival time and balance at key locations. Forcing intervals, internal steps and output intervals can differ; output timestamps do not reveal every internal step.'));
out+=detail('numerical-kdrum','05 · K-DRUM 기능과 계산 경로 연결','05 · Connecting these ideas to K-DRUM paths',
 p('아래는 현재 K-DRUM의 계산 방식과 공개 기능 설명을 함께 정리한 내용입니다. 같은 기능군 안에서도 시간적분법과 경계조건의 조합이 다를 수 있으며, 기능별 개발상태는 각 항목의 표시를 따릅니다.','This overview summarizes the currently reviewed K-DRUM calculation approaches alongside the public capability descriptions. Options within a family may use different time-integration and boundary-condition combinations; interpret each one within its stated development status.')+
 `<dl class="path-notes"><dt>${L('사면·하도 운동파','Hillslope / channel kinematic routing')}</dt><dd>${L('현재 확인된 운동파 계산은 새 저장상태의 유출을 연속식에 반영하는 후진형 보존 갱신을 사용하며 비선형 저장–유출 관계를 풉니다. 상류·국소 유입도 이 저장 계산에 함께 들어가므로, 침투로 결정된 유출 생성과 하류 전달을 구분해 해석해야 합니다.','The currently reviewed kinematic calculation uses a backward-type conservative update and solves a nonlinear storage–outflow relation, including upstream and local inputs. Interpret runoff generation separately from downstream routing.')} <a href="#cap-kw-river">${L('하도 운동파','Channel kinematic wave')} →</a></dd><dt>${L('2D 확산파·국부관성','2D diffusion / local inertia')}</dt><dd>${L('수면차로 경계 유량을 계산하는 방식과 이전 유량의 시간 변화를 유지하는 방식을 구분합니다. 현재 확인된 국부관성 계산은 수면차에 의한 구동에 이전 유량을 반영하고 마찰항을 반음해(semi-implicit) 방식으로 처리합니다. 국부관성은 관성을 모두 생략한 확산파와 다릅니다.','Distinguish a surface-gradient flow calculation from one that retains the time evolution of previous flow. The currently reviewed local-inertia calculation combines previous flow with surface-gradient forcing and a semi-implicit friction treatment; it is distinct from diffusion wave.')} <a href="#cap-local-inertia">Local Inertia →</a></dd><dt>${L('1D 하천망','1D river networks')}</dt><dd>${L('횡단면과 하천망 연결정보를 사용하는 수리 계산에는 여러 개발 방식이 있습니다. 동역학파 구성요소, 국부관성 기반 방식, 독립적인 음해 시간적분 구성요소를 하나의 기본 알고리즘으로 묶지 않으며, 실제 모의에서 선택한 계산 방식을 기준으로 해석합니다.','Several hydraulic calculation options use cross sections and network connectivity. Dynamic-wave components, local-inertia options and standalone implicit integration components are not one universal default algorithm; interpretation must follow the calculation mode selected for the simulation.')} <a href="#cap-dwnet">DWNET →</a></dd><dt>Full SWE</dt><dd>${L('현재 확인된 Full SWE 계산은 유한체적형 보존 갱신과 HLL 계열의 경계면 플럭스를 사용합니다. 공간 복원과 시간적분에는 1차·2차 선택 방식이 있으며, 지형 영향·마찰·건습 처리가 함께 적용됩니다. 시간간격은 수심·유속에 따른 파동 전파를 고려하므로 작은 셀이나 빠른 흐름이 계산 비용에 영향을 줍니다.','The currently reviewed Full SWE calculation uses finite-volume conservative updates and HLL-family face fluxes. First- and second-order reconstruction and time-integration options are available, together with terrain effects, friction and wet/dry treatment. Wave speeds associated with depth and velocity constrain the time step, so small cells or fast flow can raise computational cost.')} <a href="#cap-fullswe">Full SWE →</a></dd></dl>`+
 p('기법명이 같아도 경계조건·구조물·연계 방식의 지원 조합은 달라질 수 있습니다. 실행본의 문서와 기능별 적용 범위를 함께 확인해 비교 조건을 맞춥니다.','Even with the same method name, supported boundary, structure and coupling combinations can differ. Use build documentation and capability scope to establish comparable cases.'));
out+=detail('numerical-boundaries','06 · 경계조건·건습·검증에서 읽을 것','06 · Boundaries, wet/dry fronts and verification',
 h('경계조건은 외부 세계와 연결하는 식입니다','Boundary conditions connect the model to its surroundings')+p('유입 유량, 하류 수위, 조위, 벽과 개방 경계는 각각 다른 정보를 제공합니다. 아임계 흐름에서는 하류 수위의 영향이 상류로 전달될 수 있어 유입량만으로 수위를 결정할 수 없습니다. 경계의 개수와 종류는 유동 상태와 해석 경로에 맞춰야 합니다.','Inflow discharge, downstream stage, tide, walls and open boundaries provide different information. Subcritical flow can transmit downstream-stage influence upstream; inflow alone does not determine stage. Boundary number and type must suit the flow regime and solver.')+
 h('마름 처리는 음의 물을 만들지 않는 문제입니다','Wetting and drying require physically admissible storage')+p('얕은 셀에서 너무 많은 물이 빠져나가면 음의 수심이 생길 수 있습니다. 가용량에 맞춘 유출 처리와 건습 판정이 필요하며, 임계값 부근 유속은 작은 수심으로 나누기 때문에 민감할 수 있습니다. 단순히 수심을 0으로 바꾼 뒤 물수지를 확인하지 않는 것은 충분하지 않습니다.','Excessive outflow from a shallow cell can produce negative depth. Available-water limits and wet/dry handling are needed; velocity near a depth threshold is sensitive because it divides discharge by small depth. Clipping depth alone is not a conservation check.')+
 `<ol class="verification-list"><li>${L('정지 수면: 지형이 달라도 정지 상태에서 인위적인 흐름이 생기지 않는가.','Lake at rest: does varying terrain create artificial flow in a resting state?')}</li><li>${L('보존: 경계·소스·손실·저장 변화가 같은 기간과 단위로 맞는가.','Conservation: do boundary fluxes, sources, losses and storage change balance?')}</li><li>${L('전파·건습: 유입 변화가 전달되는 시각과 침수 전선이 해상도·시간간격에 민감한가.','Propagation and fronts: how sensitive are arrival times and wetting fronts to grid and timestep?')}</li><li>${L('관측 비교: 수위·유량·침수 범위를 독립 자료와 비교했는가.','Observations: have stage, discharge and inundation been compared with independent data?')}</li></ol>`+
 p('이 목록은 사용자가 해석 품질을 판단하는 기준입니다. 홈페이지에 기능이 소개되어 있다는 사실만으로 모든 항목의 검증을 통과했다는 의미는 아닙니다.','These are criteria for assessing a simulation, not a claim that every listed capability has passed every test.')+
 `<p class="small">${L('수면경사와 이산화의 이론 참고','Further theory on surface gradients and discretization')}: <a href="https://www.hec.usace.army.mil/confluence/rasdocs/ras1dtechref/6.5/theoretical-basis-for-one-dimensional-and-two-dimensional-hydrodynamic-calculations/2d-unsteady-flow-hydrodynamics/numerical-methods/diffusion-wave-equation-solver">USACE · Diffusion-wave solver</a>. ${L('외부 문헌은 일반 이론의 출처이며 K-DRUM의 동일 구현·성능을 뜻하지 않습니다.','External references explain general theory, not identical K-DRUM implementation or performance.')}</p>`);
out+='</div></section>';return out;}
module.exports={render,feature};
